### ISSUE TITLE
linkerd send traffic to retired servers

### ISSUE THREAD

**Issue by pengfei-xue** [linkerd/linkerd#2283] opened 2019-06-13 02:43 UTC
# Thanks for your help improving the project! #

## Getting Help ##

Github issues are for bug reports and feature requests. For questions about
Linkerd, how to use it, or debugging assistance, start by
[asking a question in the forums](https://discourse.linkerd.io/) or join us on
[Slack](https://slack.linkerd.io/).

Full details at [CONTRIBUTING.md](https://github.com/linkerd/linkerd/blob/master/CONTRIBUTING.md).

## Filing a Linkerd issue ##

Issue Type:

- [ x] Bug report
- [ ] Feature request

**What happened**:
i'm using linkerd 1.4.6, we use namerd with consul to do service discovery, 
we added some new servers for one service, and retired some servers, 
updated configs in consul, some linkerd instances got the right addrs for that service, 
but some still sent traffic to the retired ip

use this namerd api `/api/1/resolve/gm?path=/svc/prod/gaia` get the right addrs
but call the linkerd api `/client_state.json` give me the wrong addrs(old retired addr returned).

**What you expected to happen**:
after update consul, linkerd instance should not send traffic to retired servers

**How to reproduce it (as minimally and precisely as possible)**:
don't know

**Anything else we need to know?**:

**Environment**:

linkerd/namerd version, config files:

```
     routers:
- protocol: http
  maxRequestKB: 51200
  label: gm-http
  httpAccessLog: /data/log/gm-linkerd/access.log
  httpAccessLogRollPolicy: daily
  httpAccessLogAppend: true
  httpAccessLogRotateCount: 1
  bindingTimeoutMs: 1000
  interpreter:
    kind: io.l5d.namerd
    dst: /$/inet/namerd.prod.gengmei/4100
    namespace: gm

  client:
    kind: io.l5d.global
    loadBalancer:
      kind: ewma
    failureAccrual:
      kind: io.l5d.consecutiveFailures
      failures: 10
```

```
      namers:
- kind: io.l5d.consul
  host: 127.0.0.1
  port: 8500
  includeTag: true
  useHealthCheck: false
  healthStatuses:
    - "passing"
    - "warning"
  setHost: false
  consistencyMode: stale
  failFast: true

storage:
  kind: io.l5d.consul
  host: 127.0.0.1
  port: 8500
  pathPrefix: /namerd/dtabs

interfaces:
- kind: io.l5d.thriftNameInterpreter
  ip: 0.0.0.0
  port: 4100

- kind: io.l5d.httpController
  ip: 0.0.0.0
  port: 4180
```

- Platform, version, and config files (Kubernetes, DC/OS, etc): linux vm centos7.5
- Cloud provider or hardware configuration:

**Comment by dadjeibaah** [comment] 2019-06-13 16:31
@pengfei-xue, thanks for filing this. I noticed that you are using Namerd's thrift interpreter to get SD updates from Consul. Are you able to try the `io.l5d.mesh` interpreter to see if you run into this issue?

**Comment by pengfei-xue** [comment] 2019-06-14 03:30
> @pengfei-xue, thanks for filing this. I noticed that you are using Namerd's thrift interpreter to get SD updates from Consul. Are you able to try the `io.l5d.mesh` interpreter to see if you run into this issue?

why should i try io.l5d.mesh? is there any specific reason?
btw, i can't reproduce this bug, but it do affect 20+ nodes in our prod env.

**Comment by dadjeibaah** [comment] 2019-06-17 23:40
> why should I try io.l5d.mesh? is there any specific reason?

The `io.l5d.mesh` seems to perform better and runs into fewer issues w.r.t to stale service discovery. We've been encouraging users to transition to the mesh interpreter if they've been using the thrift interpreter.

**Comment by chrisgoffinet** [comment] 2019-06-18 13:15
I can concur, at Credit Karma we've seen better results. We were using Thrift for a long time with various subtle bugs.

**Comment by adleong** [comment] 2019-07-01 22:07
@pengfei-xue how is this going?  are you still experiencing the issue?  have you had a chance to try the mesh interpreter?

**Comment by hukaixuan** [comment] 2019-07-02 07:16
> @pengfei-xue how is this going? are you still experiencing the issue? have you had a chance to try the mesh interpreter?

I work together with @pengfei-xue . we still using io.l5d.thriftNameInterpreter in our production environment and meet the same issue again. we will think about try the mesh interpreter and give feed back if there is a progress.

**Comment by cpretzer** [comment] 2019-07-16 01:29
@hukaixuan did you have any luck using the mesh interpreter?

**Comment by dadjeibaah** [comment] 2019-07-23 16:31
@hukaixuan any update on this issue?

**Comment by hukaixuan** [comment] 2019-07-24 02:38
@dadjeibaah @cpretzer  sorry for replay late, we can't reproduce this issue in our test environment and need be careful with doing change in our prod environment. busy with doing other things these days, have no chance to verify this change in prod. If there is any update, will feed back ASAP. Thanks for your help : )

**Comment by adleong** [comment] 2019-07-30 16:35
Thanks, @hukaixuan.  I'm going to close this issue for now.  Please re-open this or open a new issue if you see this problem again.

**Closed by adleong** 2019-07-30 16:35 UTC
