### ISSUE TITLE
Responses from HTTP 1.0 servers get stuck

### ISSUE THREAD

**Issue by robertpanzer** [linkerd/linkerd#1978] opened 2018-06-08 08:48 UTC
Issue Type:

- [X] Bug report
- [ ] Feature request

**What happened**:

Routed a request to a server that responds with HTTP 1.0 without `content-length` header, e.g. a simple Python server.
Since Linkerd 1.4.1 the response body doesn't reach the client anymore, only the headers arrive.

**What you expected to happen**:

I expect to get the full response.

**How to reproduce it (as minimally and precisely as possible)**:

Start Linkerd with this configuration:

```yaml
admin:
  port: 9990
  ip: 0.0.0.0

routers:
- protocol: http
  dtab: |
    /svc => /$/inet/localhost/8082;
  httpAccessLog: logs/access.log
  label: rt
  servers:
  - port: 4140
    ip: 0.0.0.0
```

Start this python script with `./simple-server.py 8082`:

```python
#!/usr/bin/env python
from BaseHTTPServer import BaseHTTPRequestHandler, HTTPServer
import SocketServer

port_number = 80

class S(BaseHTTPRequestHandler):
    def _set_headers(self):
        self.send_response(200)
        self.send_header('Content-type', 'text/plain')
        self.end_headers()

    def do_GET(self):
        self._set_headers()
        self.wfile.write("hello, from port: " + `port_number`)

def run(server_class=HTTPServer, handler_class=S, port=80):
    global port_number
    port_number = port
    server_address = ('', port_number)
    httpd = server_class(server_address, handler_class)
    print 'Starting httpd...'
    httpd.serve_forever()

if __name__ == "__main__":
    from sys import argv

    if len(argv) == 2:
        run(port=int(argv[1]))
    else:
        run()
```

Then start the plain linkerd-exec version 1.4.1 with this configuration file and run this call:

```
$ curl -v localhost:4140                                                
* Rebuilt URL to: localhost:4140/
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 4140 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 4140 (#0)
> GET / HTTP/1.1
> Host: localhost:4140
> User-Agent: curl/7.54.0
> Accept: */*
>
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Via: 1.0 linkerd
< l5d-success-class: 1.0
< Date: Fri, 08 Jun 2018 08:40:38 GMT
* HTTP/1.0 connection set to keep alive!
< Connection: keep-alive
< Server: BaseHTTP/0.3 Python/2.7.15
< Content-type: text/plain
<
```

curl is stuck now and doesn't terminate.
With 1.4.0 the full response arrives at the client.

Netstat looks like this while the call is blocked:

```
$ netstat -an|grep 8082
tcp4       0      0  *.8082                 *.*                    LISTEN
$ netstat -an|grep 4140
tcp4       0      0  127.0.0.1.4140         127.0.0.1.59227        ESTABLISHED
tcp4       0      0  127.0.0.1.59227        127.0.0.1.4140         ESTABLISHED
tcp4       0      0  *.4140                 *.*                    LISTEN 
```

It looks like the simple server has correctly closed the connection.

**Environment**:
- linkerd/namerd version, config files:
Linkerd 1.4.1 with the config shown above
- Platform, version, and config files (Kubernetes, DC/OS, etc):
Plain OS X, no fancy container stuff or orchestrators
- Cloud provider or hardware configuration:
MacBook 2013

**Comment by robertpanzer** [comment] 2018-06-08 09:05
These are the network captures of these calls with 1.4.0 and 1.4.1.
With 1.4.1 Linkerd seems to no longer act as a HTTP 1.1. server if the backend talks 1.0.

[linkerd1.4.0.log](https://github.com/linkerd/linkerd/files/2083700/linkerd1.4.0.log)
[linkerd1.4.1.log](https://github.com/linkerd/linkerd/files/2083701/linkerd1.4.1.log)

**Comment by dadjeibaah** [comment] 2018-06-08 18:22
@robertpanzer thanks for all the detail you've included in this issue. We will run through your steps and see what might be going on.

**Comment by adleong** [comment] 2018-06-14 00:14
I think this was caused by https://github.com/linkerd/linkerd/pull/1904

What seems to be happening is that the HTTP/1.0 server is closing the connection to signal the end of the response (as opposed to using Content-Length or Transfer-Encoding).  However, Linkerd will set `Connection: keep-alive` on the response and keep the connection to the client (curl) alive.  Therefore, the absence of Content-Length, Transfer-Encoding, or connection termination will mean that curl cannot detect that the message has completed.

**Closed** 2018-06-15 17:56 UTC
