### ISSUE TITLE
NullpointerException on non-resolvable DNS + stall DNS

### ISSUE THREAD

**Issue by leozc** [linkerd/linkerd#1387] opened 2017-06-13 23:58 UTC
This issue is with the following topology:
Linkerd -> namerd -> consul

Consul stores the service info and address  is an elb DNS [ x ]

Here is the observation:
if x doesn’t exist -> linkerd reports nullpointexception for the specific dst
And by adding x into R53, still nullpointerexception (yes: **ttl** is set : networkaddress.cache.ttl=30 )
Restart Linkerd solved the problem

Repro on 1.1.0 linkerd / namerd 
```
un 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]: E 0613 23:50:37.457 UTC THREAD29 TraceId:1dfda261a57b95cd: addr on /#/io.l5d.consul/us-east-1/integration/clicktocall
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]: org.apache.thrift.TApplicationException: Internal error processing addr: 'java.lang.NullPointerException'
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at org.apache.thrift.TApplicationException.read(TApplicationException.java:108)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.buoyant.namerd.iface.thriftscala.Namer$FinagleClient.decodeResponse(Namer$FinagleClient.scala:65)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.buoyant.namerd.iface.thriftscala.Namer$FinagleClient.$anonfun$addr$1(Namer$FinagleClient.scala:170)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.finagle.thrift.DeserializeCtx.deserialize(DeserializeCtx.scala:38)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.buoyant.namerd.iface.thriftscala.Namer$FinagleClient.$anonfun$addr$3(Namer$FinagleClient.scala:194)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.util.Future.$anonfun$flatMap$1(Future.scala:1089)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.util.Promise$Transformer.liftedTree1$1(Promise.scala:107)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.util.Promise$Transformer.k(Promise.scala:107)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.util.Promise$Transformer.apply(Promise.scala:117)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.util.Promise$Transformer.apply(Promise.scala:98)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.util.Promise$$anon$1.run(Promise.scala:421)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:200)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:158)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:272)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:108)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.util.Promise.runq(Promise.scala:406)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.util.Promise.updateIfEmpty(Promise.scala:801)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.util.Promise.update(Promise.scala:775)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.util.Promise.setValue(Promise.scala:751)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.concurrent.AsyncQueue.offer(AsyncQueue.scala:123)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.finagle.netty4.transport.ChannelTransport$$anon$1.channelRead(ChannelTransport.scala:181)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.finagle.netty4.codec.BufCodec$.channelRead(BufCodec.scala:59)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.finagle.netty4.channel.AnyToHeapInboundHandler$.channelRead(AnyToHeapInboundHandler.scala:36)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.finagle.netty4.channel.ChannelRequestStatsHandler.channelRead(ChannelRequestStatsHandler.scala:42)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.finagle.netty4.channel.ChannelStatsHandler.channelRead(ChannelStatsHandler.scala:92)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:624)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:559)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:476)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:24)
Jun 13 23:50:37 ip-172-23-23-249 linkerd-1.1.0-exec[23557]:         at java.lang.Thread.run(Thread.java:748)
```

**Comment by leozc** [comment] 2017-06-13 23:58
Repro on 
L5D 1.1 and Namerd 1.1

**Comment by wmorgan** [comment] 2017-06-14 06:34
Thanks @leozc. We'll take a look!

**Comment by leozc** [comment] 2017-06-15 02:50
Interesting that means the DNS resolving is on namerd ? Let me dig ...

**Comment by adleong** [comment] 2017-06-20 21:02
Hi @leozc, were you able to get those namerd logs?

**Comment by leozc** [comment] 2017-06-21 03:29
I have been out of town - will try to get the log when I am back.

Cheers
Leo@mobile

**Comment by leozc** [comment] 2017-06-28 23:27
```
W 0628 23:24:22.620 UTC THREAD20: Exception propagated to the default monitor (upstream address: /172.23.32.183:62799, downstream address: n/a, label: adminhttp).
java.lang.NullPointerException
        at io.buoyant.admin.names.DelegateApiHandler$Address$.mk(DelegateApiHandler.scala:34)
        at io.buoyant.admin.names.DelegateApiHandler$Addr$.$anonfun$mk$1(DelegateApiHandler.scala:57)
        at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
        at scala.collection.immutable.Set$Set1.foreach(Set.scala:95)
        at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
        at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
        at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
        at io.buoyant.admin.names.DelegateApiHandler$Addr$.mk(DelegateApiHandler.scala:57)
        at io.buoyant.admin.names.DelegateApiHandler$Bound$.$anonfun$mk$3(DelegateApiHandler.scala:79)
        at com.twitter.util.Future.$anonfun$map$2(Future.scala:1145)
        at com.twitter.util.Try$.apply(Try.scala:15)
        at com.twitter.util.Future$.apply(Future.scala:163)
        at com.twitter.util.Future.$anonfun$map$1(Future.scala:1145)
        at com.twitter.util.Promise$Transformer.liftedTree1$1(Promise.scala:107)
        at com.twitter.util.Promise$Transformer.k(Promise.scala:107)
        at com.twitter.util.Promise$Transformer.apply(Promise.scala:117)
        at com.twitter.util.Promise$Transformer.apply(Promise.scala:98)
        at com.twitter.util.Promise$$anon$2.run(Promise.scala:823)
        at com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:200)
        at com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:158)
        at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:272)
        at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:108)
        at com.twitter.util.Promise.runq(Promise.scala:406)
        at com.twitter.util.Promise.updateIfEmpty(Promise.scala:801)
        at com.twitter.util.Promise.update(Promise.scala:775)
        at com.twitter.util.Promise.setValue(Promise.scala:751)
        at com.twitter.concurrent.AsyncQueue.offer(AsyncQueue.scala:123)
        at com.twitter.finagle.netty3.transport.ChannelTransport.handleUpstream(ChannelTransport.scala:56)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142)
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at com.twitter.finagle.http.SafeServerHttpChunkAggregator.handleUpstream(Codec.scala:27)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.messageReceived(SimpleChannelUpstreamHandler.java:124)
        at com.twitter.finagle.http.codec.RespondToExpectContinue.messageReceived(RespondToExpectContinue.scala:28)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.messageReceived(SimpleChannelUpstreamHandler.java:124)
        at com.twitter.finagle.http.codec.PayloadSizeHandler.messageReceived(PayloadSizeHandler.scala:22)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.handler.codec.http.HttpContentEncoder.messageReceived(HttpContentEncoder.java:82)
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
        at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
        at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
        at org.jboss.netty.handler.codec.http.HttpServerCodec.handleUpstream(HttpServerCodec.java:56)
        at com.twitter.finagle.http.SafeHttpServerCodec.handleUpstream(Codec.scala:46)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
        at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
        at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
        at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
        at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:24)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by wmorgan** [comment] 2017-06-28 23:48
@leozc great, thanks!

**Comment by adleong** [comment] 2017-06-30 21:51
I'm not able to reproduce this but based on the stack trace, I believe this should fix it: https://github.com/linkerd/linkerd/pull/1460

@leozc can you take a look and let me know if that fixes the issue for you?

**Comment by leozc** [comment] 2017-06-30 22:12
Cool , which build is it?

**Comment by adleong** [comment] 2017-06-30 22:18
It hasn't been merged yet.  Are you able to build off of my branch?  If not, let me know and I can send you a build or docker image.

**Closed** 2017-07-03 20:51 UTC
