### ISSUE TITLE
Linkerd file base service recovery is not working

### ISSUE THREAD

**Issue by mnnit-geek** [linkerd/linkerd#1462] opened 2017-07-03 07:42 UTC
Hi,
I'm not able to use file based service discovery. 
Here is my directory structure:
[root@ip-172-23-1-207 aman]# ls
config  disco  index.html  linkerd-1.0.2-exec  upload

LinkerD config file looks like this:
```
[root@ip-172-23-1-207 aman]# cat config/linkerd-fs.yml
namers:
- kind: io.l5d.fs
  rootDir: disco

admin:
  ip: 172.23.1.207
  port: 8888

routers:
- protocol: http
  dtab:
        /svc => /#/io.l5d.fs ;
  servers:
  - port: 7777

telemetry:
- kind: io.l5d.recentRequests
  sampleRate: 1.0
```

[root@ip-172-23-1-207 aman]# cat disco/dcs
172.23.1.211 1212
172.23.1.133 1212
172.23.1.207 1212

Now, if I add any new server under dcs for example:
[root@ip-172-23-1-207 aman]# cat disco/dcs
172.23.1.211 1212
172.23.1.133 1212
172.23.1.207 1212
172.23.1.130 1212

The requests are not getting routed to the new VM unless I restart the LinkerD. Please suggest what could be wrong here?

**Comment by wmorgan** [comment] 2017-07-03 16:40
Are you pushing enough throughput through Linkerd that it actually needs multiple destinations?

Anything in the logs?

**Comment by adleong** [comment] 2017-07-03 16:58
The io.l5d.fs namer uses Java's WatchService (https://docs.oracle.com/javase/7/docs/api/java/nio/file/WatchService.html) under the hood.  I've noticed that it can sometimes take a while for notifications to occur after the file has been changed.  This might be what you're experiencing.

**Comment by mnnit-geek** [comment] 2017-07-03 16:59
Yes in fact I'm running an infinite while loop to push the data to my simple python web-server. There's nothing in LinkerD server logs

**Comment by mnnit-geek** [comment] 2017-07-03 17:04
@adleong Thanks for reply. Actually, I have pretty much followed your talk to do all of my setup. And I have waited for more than half-an-hour to make sure there's enough time for linkerD to detect the change, however, unfortunately it doesn't detect the changes at all. But if I restart the server it start redirecting traffic to fourth node as well.
Any idea what could be wrong here?

**Comment by adleong** [comment] 2017-07-03 17:09
@mnnit-geek: I'm not sure.  I've never had it take that long.  That's strange.

**Comment by mnnit-geek** [comment] 2017-07-03 17:22
can you suggest any checks/verifications that will help single out the possible cause of the problem?

**Comment by adleong** [comment] 2017-07-03 17:24
Perhaps try a different service discovery backend such as Consul, just to verify that the problem is limited to the filesystem namer.

**Comment by mnnit-geek** [comment] 2017-07-03 17:27
Thanks for swift response. Consul is our ultimate requirement in terms of the actual architectural implement. I have been reading on different blogs how to integrate LinkerD and Consul, but things are not very clear to me just yet. By any chance your'e aware about any good blogs or articles that can help me achieve the integration relatively easily?

**Comment by wmorgan** [comment] 2017-07-03 18:06
We have some examples on https://github.com/linkerd/linkerd-examples/tree/master/consul

FWIW I run the fs namer for various demos on a volume-mounted dir on Docker for Mac (the worst possible combination of filesystems). It can take 5-10 seconds to see a change. If it's taking more than that, there's definitely something weird going on.

**Comment by adleong** [comment] 2017-07-06 21:34
I'm going to close this for now since I haven't been able to reproduce it.  Hopefully the move to consul makes this a moot issue.

**Closed by adleong** 2017-07-06 21:34 UTC

**Comment by mnnit-geek** [comment] 2017-07-07 12:31
Well, A few of my colleagues also tried and faced the same problem. Can you suggest a way we can deduce what's going on?

**Comment by wmorgan** [comment] 2017-07-07 17:30
@mnnit-geek hopefully this issue is not a blocker if you're using Consul in production, but it would be good to figure out what's going on here.

We haven't seen this on our side, so the best way to help us is to find a reproduction case we can dig into. Is there a specific OS that this happens on? Are there specific changes to the file that don't get picked up, but others do? Does using `touch` do anything? If you run Linkerd with debug flags (see https://discourse.linkerd.io/t/debugging-a-linkerd-setup/52) are there any interesting messages in the logs? All that info would help us.
