### ISSUE TITLE
client config should support the clearContext parameter

### ISSUE THREAD

**Issue by aaronyoungkash** [linkerd/linkerd#1513] opened 2017-07-18 20:07 UTC
When falling back to DNS during dtab resolution it would be nice to strip the l5d headers from the egress request. The server-wide config already has a clearContext, applying the same logic to the client config would be helpful.

**Comment by esbie** [comment] 2017-07-18 20:40
duplicate of #1218

**Closed by esbie** 2017-07-18 20:40 UTC
