### ISSUE TITLE
HTTP 504 Gateway timeouts after upgrading to linkerd 1.2.0

### ISSUE THREAD

**Issue by kumudt** [linkerd/linkerd#1636] opened 2017-09-13 11:57 UTC
## Filing a linkerd issue ##

Issue Type: Bug Report

**What happened**:
We have a rails application which serves web pages and it was running as a Kubernetes deployment. Every time a deployment is made and new pods come up, Linkerd gives 504 gateway timeout and when I checked Linkerd logs I can see that it was still making requests to the old endpoints. (Not sure if this is a config issue). It get's fixed on its own after some time.

**What you expected to happen**:
Endpoints should be instantly updated whenever there is a deployment.

**How to reproduce it (as minimally and precisely as possible)**:
Rails Puma Server serving web pages and making requests to the service just after a deployment.

**Anything else we need to know?**:
Our router config:
```
    - protocol: http
      label: webapp-external
      identifier:
        kind: io.l5d.header.token
        header: Host
      interpreter:
        kind: io.l5d.namerd
        dst: /$/inet/namerd.linkerd.svc.cluster.local/4100
        namespace: external
        transformers:
        - kind: io.l5d.k8s.daemonset
          namespace: linkerd
          port: webapp-ingress
          service: linkerd-internal
      servers:
      - port: 4143
        ip: 0.0.0.0
      client:
        kind: io.l5d.global
        loadBalancer:
          kind: ewma
          enableProbation: false
          maxEffort: 5
          decayTimeMs: 10
        failureAccrual:
          kind: io.l5d.consecutiveFailures
          failures: 5
      service:
        kind: io.l5d.global

    - protocol: http
      label: webapp-ingress
      identifier:
        kind: io.l5d.header.token
        header: Host
      interpreter:
        kind: io.l5d.namerd
        dst: /$/inet/namerd.linkerd.svc.cluster.local/4100
        namespace: external
        transformers:
        - kind: io.l5d.k8s.localnode
      servers:
      - port: 4145
        ip: 0.0.0.0
      client:
        kind: io.l5d.global
        loadBalancer:
          kind: ewma
          enableProbation: false
          maxEffort: 5
          decayTimeMs: 10
        failureAccrual:
          kind: io.l5d.consecutiveFailures
          failures: 5
      service:
        kind: io.l5d.global
```

**Environment**:
- linkerd/namerd version, config files: 1.2.0/1.2.0
- Platform, version, and config files (Kubernetes, DC/OS, etc): Kubernetes
- Cloud provider or hardware configuration: AWS

**Comment by mejran** [comment] 2017-09-13 16:32
We hit this issue as well, however out of two linkerd ingress controllers one updated correctly to the new endpoint and one still pointed to the old endpoint. Something to watch out for since the issue may be random or configuration dependent.

**Comment by wmorgan** [comment] 2017-09-13 16:35
Thanks @kumudt, @mejran.  We'll take a look.

**Comment by hawkw** [comment] 2017-09-13 17:36
Hi @mejran and @kumudt, this looks like the same issue as #1626 and #1635. We're trying to find the cause of this problem, and hopefully we'll have a fix soon.

Thanks for reporting!

**Comment by hawkw** [comment] 2017-09-13 21:38
Hi again @kumudt and @mejran, just wanted to let you know that I've opened pull request #1638, which should fix this issue (and #1626 and #1635). We'll try and get the fix out to you as soon as possible!

**Comment by kumudt** [comment] 2017-09-14 11:00
Any workaround for this until this PR gets merged??

**Comment by kumudt** [comment] 2017-09-14 11:13
Today, we have found another issue along with this. It is not just for a single service. We have other services as well which are failing. Also, this time we didn't even do any deployments on those services which are failing. Later, we deleted all the Linkerd and Namerd pods which fixed it. This is also happening randomly.
Not sure, if your issues #1626 and #1635 explains this behavior.

**Comment by Taik** [comment] 2017-09-14 13:36
@kumudt there's no real workaround AFAIK; doing a rolling delete of linkerd pod does it for us, but its not ideal.

**Comment by hawkw** [comment] 2017-09-14 14:00
Hi @kumudt, in the meantime, you can try using the Docker image `buoyantio/linkerd:1.2.0.fix4-SNAPSHOT`, but please note this is not a production ready release yet.

**Comment by kumudt** [comment] 2017-09-15 08:57
I deployed Linkerd and Namerd 1.2.1 and made a deployment to my application. It failed just like before with 504 and I see the exact same logs in the linkerd pods.


```
[l5d-cmlms l5d] E 0915 08:47:15.837 UTC THREAD44 TraceId:22097486f9419347: service failure: Failure(connection timed out: /100.96.3.244:3000 at remote address: /100.96.3.244:3000. Remote Info: Not Available, flags=0x09) with RemoteInfo -> Upstream Address: /100.96.3.241:37030, Upstream Client Id: Not Available, Downstream Address: /100.96.3.244:3000, Downstream Client Id: %/io.l5d.k8s.localnode/100.96.3.241/#/io.l5d.k8s/webapp/webapp-server/webapp-service, Trace Id: 22097486f9419347.e6fab0ca0856059c<:db5b9130907f941d 
[l5d-cmlms l5d] E 0915 08:47:16.478 UTC THREAD37 TraceId:22097486f9419347: service failure: Failure(request cancelled. Remote Info: Upstream Address: /10.11.10.139:21963, Upstream Client Id: Not Available, Downstream Address: /100.96.3.241:4145, Downstream Client Id: %/io.l5d.k8s.daemonset/linkerd/webapp-ingress/linkerd-internal/#/io.l5d.k8s/webapp/webapp-server/webapp-service, Trace Id: 22097486f9419347.37618bd902da6cc1<:22097486f9419347, flags=0x03) with RemoteInfo -> Upstream Address: /100.96.3.241:37030, Upstream Client Id: Not Available, Downstream Address: /100.96.3.244:3000, Downstream Client Id: %/io.l5d.k8s.localnode/100.96.3.241/#/io.l5d.k8s/webapp/webapp-server/webapp-service, Trace Id: 22097486f9419347.760c2ba7b873dab5<:37618bd902da6cc1 
[l5d-cmlms l5d] E 0915 08:47:16.479 UTC THREAD42 TraceId:22097486f9419347: service failure: com.twitter.finagle.CancelledRequestException: request cancelled. Remote Info: Upstream Address: /10.11.10.139:21963, Upstream Client Id: Not Available, Downstream Address: /100.96.3.241:4145, Downstream Client Id: %/io.l5d.k8s.daemonset/linkerd/webapp-ingress/linkerd-internal/#/io.l5d.k8s/webapp/webapp-server/webapp-service, Trace Id: 22097486f9419347.37618bd902da6cc1<:22097486f9419347 
```

**Comment by hawkw** [comment] 2017-09-15 14:22
Hi @kumudt, that's disappointing to hear. Your deployments must be effected by another issue besides #1626. We'll keep looking into this.

**Comment by hawkw** [comment] 2017-09-15 14:23
Could you possibly post the configuration file for Namerd as well?

**Comment by kumudt** [comment] 2017-09-15 14:48
```
    telemetry:
    - kind: io.l5d.influxdb

    namers:
    - kind: io.l5d.k8s
      host: localhost
      port: 8001

    storage:
      kind: io.l5d.k8s
      host: localhost
      port: 8001
      namespace: linkerd

    interfaces:
    - kind: io.l5d.thriftNameInterpreter
      ip: 0.0.0.0
      port: 4100
    - kind: io.l5d.mesh
      ip: 0.0.0.0
      port: 4321
    - kind: io.l5d.httpController
      ip: 0.0.0.0
      port: 4180
```

**Comment by hawkw** [comment] 2017-09-15 15:01
Thanks!

**Comment by hawkw** [comment] 2017-09-15 16:04
Hi again @kumudt, I'm working on a reproduction for this issue, can I get you to give me an example of what steps you're using to deploy your application? I'm guessing it's `kubectl deploy`, but it would be nice to know exactly what you're doing. Thanks!

**Comment by kumudt** [comment] 2017-09-15 16:16
I am using
```
kubectl apply -f <deployment-config-file>.yaml
```
This will create new pods and delete the old ones. Also, at the end of the deployment we are deleting the old replicaset.

**Comment by hawkw** [comment] 2017-09-15 18:08
@kumudt, you've said you first observed this issue upon upgrading to Linkerd 1.2.0. Can you tell me what Linkerd version you were upgrading _from_?

**Comment by kumudt** [comment] 2017-09-15 18:11
From 1.1.2. We skipped 1.1.3. Currently, we have downgraded it to 1.1.3.

**Comment by hawkw** [comment] 2017-09-15 18:16
Are you still seeing this issue on 1.1.3?

**Comment by kumudt** [comment] 2017-09-15 18:19
No. Haven't checked much after downgrading to 1.1.3. But, don't think so. We have seen it significantly in 1.2.0 and 1.2.1

**Comment by hawkw** [comment] 2017-09-15 19:55
Hi @kumudt, I haven't been able to reproduce this issue with Linkerd 1.2.1 and Namerd 1.2.1. Here's my Linkerd configuration:
```yaml
    routers:
    - protocol: http
      label: outgoing
      identifier:
        kind: io.l5d.header.token
        header: Host
      interpreter:
        kind: io.l5d.namerd
        dst: /$/inet/namerd.liza.svc.cluster.local/4100
        namespace: internal
        transformers:
        - kind: io.l5d.k8s.daemonset
          namespace: liza
          port: incoming
          service: l5d
      servers:
      - port: 4140
        ip: 0.0.0.0
      client:
        kind: io.l5d.global
        loadBalancer:
          kind: ewma
          enableProbation: false
          maxEffort: 5
          decayTimeMs: 10
        failureAccrual:
          kind: io.l5d.consecutiveFailures
          failures: 5
      service:
        kind: io.l5d.global

    - protocol: http
      label: incoming
      identifier:
        kind: io.l5d.header.token
        header: Host
      interpreter:
        kind: io.l5d.namerd
        dst: /$/inet/namerd.liza.svc.cluster.local/4100
        namespace: internal
        transformers:
        - kind: io.l5d.k8s.localnode
      servers:
      - port: 4141
        ip: 0.0.0.0
      client:
        kind: io.l5d.global
        loadBalancer:
          kind: ewma
          enableProbation: false
          maxEffort: 5
          decayTimeMs: 10
        failureAccrual:
          kind: io.l5d.consecutiveFailures
          failures: 5
      service:
        kind: io.l5d.global

    - protocol: http
      label: external
      interpreter:
        kind: io.l5d.namerd
        dst: /$/inet/namerd.liza.svc.cluster.local/4100
        namespace: external
      servers:
      - port: 4142
        ip: 0.0.0.0
      client:
        kind: io.l5d.global
        loadBalancer:
          kind: ewma
          enableProbation: false
          maxEffort: 5
          decayTimeMs: 10
        failureAccrual:
          kind: io.l5d.consecutiveFailures
          failures: 5
      service:
        kind: io.l5d.global
```
and my Namerd configuration is
```yaml
    namers:
    - kind: io.l5d.k8s
      experimental: true
      host: localhost
      port: 8001

    storage:
      kind: io.l5d.k8s
      host: localhost
      port: 8001
      namespace: default

    interfaces:
    - kind: io.l5d.thriftNameInterpreter
      ip: 0.0.0.0
      port: 4100
    - kind: io.l5d.httpController
      ip: 0.0.0.0
      port: 4180
```

I've taken the following steps to reproduce:

1. deployed Linkerd and Namerd with `kubectl -n liza apply -f`
2. deploy the `hello` and `world` services with `kubectl -n liza apply -f hello_world.yml`
3. `curl -H 'Host: hello' -s $L5D_INGRESS_LB:4140`, Linkerd routes correctly to the `hello` and `world` services, as expected
4. change the image versions in the config file for the `hello` and `world` to ensure they will be redeployed
5. deploy again with `kubectl -n liza apply -f hello_world.yml`
6. `curl -H 'Host: hello' -s $L5D_INGRESS_LB:4140` / `curl -H 'Host: world' -s $L5D_INGRESS_LB:4140`
7. Linkerd routes correctly to the new endpoints, and I don't see any error messages in the logs

I've repeated the deployment a few times, and I'm still not seeing any problems.

Please let me know if there's something I'm missing, I've tried to match your configuration as closely as possible.

**Comment by kumudt** [comment] 2017-09-17 18:10
Configuration looks similar to ours. Even for us, sometimes it was routing correctly to the new endpoints and sometimes it breaks with those error logs.
Also, In a couple of cases, it worked fine just after the deployment but started to fail after some time with the same error logs (And there were no pod terminations / reschedule operations).

**Comment by hawkw** [comment] 2017-09-17 22:18
Interesting. I retried `curl`ing repeatedly but couldn't get it to fail. When you say that it worked fine after the deployment but started to fail later, about how long after the deployment did you start to see failures?

**Comment by kumudt** [comment] 2017-09-18 03:44
Not sure. I will do one thing. I will redeploy 1.2.1 again. Are there any specific metrics that you are interested in? We are pushing Linkerd metrics to influxdb.

**Comment by kumudt** [comment] 2017-09-18 06:27
I upgraded to 1.2.1 and all services started to fail with error `No hosts are available for /svc/<hostname>, Dtab.base=[], Dtab.local=[]. Remote Info: Not Available`.
No deployments happened before and after the upgrade.
This is the error stack in Linkerd logs.

```
[l5d-ng1p1 l5d] E 0918 06:21:18.857 UTC THREAD43: [S L:/100.96.3.71:4150 R:/100.96.3.74:33350] dispatcher failed 
[l5d-ng1p1 l5d] com.twitter.finagle.ChannelClosedException: ChannelException at remote address: /100.96.3.74:33350. Remote Info: Not Available 
[l5d-ng1p1 l5d] at com.twitter.finagle.netty4.transport.ChannelTransport$$anon$1.channelInactive(ChannelTransport.scala:186) 
[l5d-ng1p1 l5d] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) 
[l5d-ng1p1 l5d] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) 
[l5d-ng1p1 l5d] at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) 
[l5d-ng1p1 l5d] at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) 
[l5d-ng1p1 l5d] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) 
[l5d-ng1p1 l5d] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) 
[l5d-ng1p1 l5d] at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) 
[l5d-ng1p1 l5d] at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) 
[l5d-ng1p1 l5d] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) 
[l5d-ng1p1 l5d] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) 
[l5d-ng1p1 l5d] at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) 
[l5d-ng1p1 l5d] at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) 
[l5d-ng1p1 l5d] at com.twitter.finagle.netty4.channel.ChannelRequestStatsHandler.channelInactive(ChannelRequestStatsHandler.scala:36) 
[l5d-ng1p1 l5d] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) 
[l5d-ng1p1 l5d] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) 
[l5d-ng1p1 l5d] at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) 
[l5d-ng1p1 l5d] at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) 
[l5d-ng1p1 l5d] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) 
[l5d-ng1p1 l5d] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) 
[l5d-ng1p1 l5d] at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) 
[l5d-ng1p1 l5d] at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:360) 
[l5d-ng1p1 l5d] at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:325) 
[l5d-ng1p1 l5d] at io.netty.handler.codec.http2.Http2ConnectionHandler.channelInactive(Http2ConnectionHandler.java:390) 
[l5d-ng1p1 l5d] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) 
[l5d-ng1p1 l5d] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) 
[l5d-ng1p1 l5d] at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) 
[l5d-ng1p1 l5d] at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) 
[l5d-ng1p1 l5d] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) 
[l5d-ng1p1 l5d] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) 
[l5d-ng1p1 l5d] at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) 
[l5d-ng1p1 l5d] at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) 
[l5d-ng1p1 l5d] at com.twitter.finagle.netty4.channel.ChannelStatsHandler.channelInactive(ChannelStatsHandler.scala:115) 
[l5d-ng1p1 l5d] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) 
[l5d-ng1p1 l5d] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) 
[l5d-ng1p1 l5d] at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) 
[l5d-ng1p1 l5d] at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1329) 
[l5d-ng1p1 l5d] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) 
[l5d-ng1p1 l5d] at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) 
[l5d-ng1p1 l5d] at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:908) 
[l5d-ng1p1 l5d] at io.netty.channel.AbstractChannel$AbstractUnsafe$7.run(AbstractChannel.java:744) 
[l5d-ng1p1 l5d] at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) 
[l5d-ng1p1 l5d] at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403) 
[l5d-ng1p1 l5d] at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462) 
[l5d-ng1p1 l5d] at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) 
[l5d-ng1p1 l5d] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) 
[l5d-ng1p1 l5d] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) 
[l5d-ng1p1 l5d] at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:24) 
[l5d-ng1p1 l5d] at java.lang.Thread.run(Thread.java:748) 
[l5d-ng1p1 l5d] 
```

**Comment by hawkw** [comment] 2017-09-18 14:58
Also, @mejran and @Taik, can you confirm that you're no longer seeing this kind of issue on 1.2.1? That could help us to pin down any aspects of @kumudt's deployment that are linked with this problem. Thanks!

**Comment by kumudt** [comment] 2017-09-18 15:16
@hawkw Our Kubernetes version was 1.7.3 and the linkerd sidecar kubectl which we were using was 1.7.3 as well.

**Comment by hawkw** [comment] 2017-09-18 15:32
Ah, interesting – I was trying to reproduce with Kubernetes 1.6.9. I'll see if there were any changes that may effect this issue.

**Comment by Taik** [comment] 2017-09-18 16:44
@hawkw we can no longer reproduce this issues in our synthetic tests (scaling up and down replica sets). Our kubernetes version is 1.7.3, linkerd 1.2.1, kubectl 1.6.2.

**Comment by hawkw** [comment] 2017-09-18 17:30
Thanks @Taik!

**Comment by kumudt** [comment] 2017-09-18 17:55
Should I change my sidecar kubectl to 1.6.2 as well and test??

**Comment by hawkw** [comment] 2017-09-18 18:20
@kumudt it's certainly worth trying!

**Comment by adleong** [comment] 2017-09-18 18:58
Hi @kumudt, I've got a few more questions to make sure I understand the issue.  Please let me know if this is correct:

Under Linkerd versions 1.1.2 and 1.1.3 everything works as expected (though there are perhaps some spurious messages in the logs).

Under Linkerd versions 1.2.0 and 1.2.1 there are two errors scenarios:

1. When you attempt to send a request through Linkerd, `No hosts are available for /svc/<hostname>, Dtab.base=[], Dtab.local=[]. Remote Info: Not Available` is returned.  Does this start happening immediately after Linkerd is deployed?  Does it happen all the time, or only for a fraction of requests?  This type of error is usually a configuration error related to dtabs or transformers.  The best way to debug is to visit the admin dashboard that Linkerd serves on port 9990 and type `/svc/<hostname>` into the dtab playground to see how Linkerd is attempting to route the request.  If you can provide a screenshot of the result, we can help you make sense of it.

2. When a service deployment happens, requests to that service start returning status code 504 and the Linkerd logs indicate that Linkerd is attempting to connect to the IP addresses of the deleted pods.  Does this only happen after deployments, or can it happen randomly as well?  If it happens _not_ after a deployment, what do the IP addresses that Linkerd is attempting to connect to correspond to?  What you describe sound like the exact symptoms of an issue that was fixed in 1.2.1 so I'm surprised that you're still experiencing it.  If you use the dtab playground to resolve `/svc/<hostname>` does it show the new pod IPs or the old pod IPs?  Can you provide a screenshot of this as well?

**Comment by kumudt** [comment] 2017-09-18 21:29
@adleong I think scenario two is fixed now (after 1.2.1)
I don't think scenario one is a dtab config issue, because we were using the same dtabs for a long time and number of errors increased after 1.2.0. It won't happen all the time. 
This is the snapshot of the dtab playground.
[Snapshot](https://www.dropbox.com/s/cwh8wk8zpzfrys1/Screen%20Shot%202017-09-19%20at%202.55.02%20AM.png?dl=0)

**Comment by adleong** [comment] 2017-09-18 21:46
That's great to hear that 1.2.1 seems to have resolved scenario two!  

Are you able to narrow down at all the conditions under which scenario one happens?  It is very difficult for us to track down without either reproduction steps or some more specific information about what's different when the issue is happening compared to when it's not.

**Comment by kumudt** [comment] 2017-09-19 09:59
@adleong I will try to reproduce it. If not we can close this issue (except for the one service rest of them are fine from the last 24 hours).

Also, a specific case when we are seeing this log
```
[l5d-ng1p1 l5d] E 0919 09:48:54.612 UTC THREAD39 TraceId:ca275f25b938a41e: service failure: com.twitter.finagle.ChannelClosedException: ChannelException at remote address: /100.96.3.173:3000 from service: %/io.l5d.k8s.localnode/100.96.3.71/#/io.l5d.k8s/webapp/webapp-server/webapp-service. Remote Info: Upstream Address: /100.96.15.248:35286, Upstream Client Id: Not Available, Downstream Address: /100.96.3.173:3000, Downstream Client Id: %/io.l5d.k8s.localnode/100.96.3.71/#/io.l5d.k8s/webapp/webapp-server/webapp-service, Trace Id: ca275f25b938a41e.d5de0d6d57a2490c<:3347c074369404ad 
```
is when the server is returning 403. Not sure if this is a config issue. If not, why isn't it returning the true response from the server. Linkerd is sending 200 in this case with an error message.

**Comment by Taik** [comment] 2017-09-19 12:03
Following up on this, it might or might not be related. If it is not then I can create a new issue. I'm sporadically seeing the same error noted by @kumudt after doing deploys.

Here's some interesting logs entries that I found: https://gist.github.com/Taik/4879143d6146bab6cfaed7dda00d6aa6

If I'm understanding the log message correctly, sometimes it marks the whole namespace as down? If that's the case then that would explain why only sometimes new pods don't get picked up instantly (and old pods removed). If kubectl loses its connection with the master, would that do it?

**Comment by kumudt** [comment] 2017-09-19 13:15
Even I have observed the endpoint watch errors and restarting all l5d pods fixed that.

**Comment by Taik** [comment] 2017-09-19 14:59
@hawkw some more logs from our dev cluster: https://gist.github.com/Taik/4879143d6146bab6cfaed7dda00d6aa6#file-service-endpoints-watch-error-log

It looks like when there are watch errors (related to kubectl?), no pods gets updated.

**Comment by adleong** [comment] 2017-09-19 17:33
@Taik: yes, from those logs it looks like Linkerd cannot connect to the k8s master API.  This could be due to an issue with the k8s master or a network issue.  If Linkerd cannot communicate with the master, it will not be able to receive service discovery updates.

**Comment by Taik** [comment] 2017-09-19 18:21
@adleong that makes a lot of sense, thanks for clarifying! Do you have any suggestions as to how to mitigate the issue? We're running on GKE so pretty vanilla in terms of setup. With the sporadic network issues, it makes it really hard for us to get things out to production without any downtime.

I do want to mention that the sidecar proxy (buouyantio/kubectl) we're using is the one that is suggested by one of the guides (1.6.2), and it seems like there are no newer versions [here](https://hub.docker.com/r/buoyantio/kubectl/tags/).

**Comment by adleong** [comment] 2017-09-19 18:26
There's not much that can be done in terms of mitigation if Linkerd can't reach the master.  Linkerd already caches results and attempt to reconnect.  I recommend trying to diagnose the cause of the connection problem.  You may want to look at a TCP dump to see why the connection is being lost.

**Comment by kumudt** [comment] 2017-09-20 10:22
Kubernetes master we are able to reach. It was not down. May be something was changed in the way the communication is happening with the K8s master, because I am not seeing these watch error logs with Linkerd 1.1.2 and the same K8s version 1.7.3.

**Comment by Taik** [comment] 2017-09-20 12:35
After reverting to `1.1.2` for the last 24 hours, I haven't seen any of the errors mentioned above, even after doing re-deploys. I'll let it bake for another few days and report back if anything crops up.

**Comment by bseibel** [comment] 2017-09-20 15:37
We're seeing this same problem in GKE with the same watch errors that @Taik is seeing. Also using linkerd/namerd 1.2.1, though to be fair we have seen this problem crop up in prior 1.1.x releases too. 

It is definitely intermittent and doesn't affect all of our running namerds at the same time. It does eventually get the correct endpoints if left alone, but it will still miss new updates. Usually restarting our linkerd and namerd pods will allow it to resume working without further issue for a time.

I havent looked too deeply yet but wondering if it could be related to error handling and https://github.com/kubernetes/kubernetes/issues/35068

**Comment by hawkw** [comment] 2017-09-20 16:19
@bseibel I've been looking into this some more today and I agree that this issue is almost certainly related to kubernetes/kubernetes#35068. That also explains why our unit tests haven't caught this issue, as the tests for handling the "too old resource version" response set the response status code to 410.

**Closed** 2017-09-20 19:09 UTC
Labels: bug, kubernetes, needs repro

**Comment by bseibel** [comment] 2017-10-03 20:17
So unfortunately we're still seeing this issue even with the fix here, we now see in debug logs 

```
D 1003 19:20:25.158 UTC THREAD51 TraceId:9921f7129139749d: k8s returned 'too old resource version' error with incorrect HTTP status code, restarting watch
```

however where we do see lines like (and pardon my slightly filtered log lines without the endpoints):

```
E  D 1003 19:51:13.636 UTC THREAD65 TraceId:8b3991f3b0f04b0d: k8s ns default svc yarisgrmn constructed new ServiceEndpoints with:
E  D 1003 19:51:13.636 UTC THREAD65 TraceId:8b3991f3b0f04b0d: k8s ns default service yarisgrmn added port mappings
E  D 1003 19:51:13.636 UTC THREAD65 TraceId:8b3991f3b0f04b0d: k8s ns default service yarisgrmn added endpoints

``` 

for most pre-existing endpoints which is fine, and expected, but a service that was added after the restarting watch line doesn't appear in the logs at all, and linkerd ends up giving us "No hosts are available".

So far we've only seen this happen in production, but it happens pretty frequently, sometimes minutes after we kick our namerd pods. Linkerd isnt logging any issues about connectivity to namerd. I'm out of town at the moment and I'm going to try to narrow down the issue further when I'm back later this week, but if theres anything specific you would like me to poke at to help narrow down the issue please let me know.

**Comment by hawkw** [comment] 2017-10-03 21:41
Hi @bseibel, thanks for following up! 

The namer should watch each service Kubernetes API object individually, so restarting a watch on a given service _shouldn't_ effect a different service that was added after the watch is restarted. It's possible something else is up. I'll be happy to continue looking into this.

Just so that I'm sure, what Linkerd/Namerd/Kubernetes versions are you using?

**Comment by bseibel** [comment] 2017-10-04 15:35
Thanks for looking into this @hawkw 

Both linkerd/namerd were the nightly at rev: b5cd1c168873d1d668b5f4fdbd729a44122135d2
Kubernetes is running out of Google Container Engine, with the master currently at 1.6.10-gke.1

**Comment by hawkw** [comment] 2017-10-04 15:53
Okay, thank you @bseibel. I'll try to determine whether what you're experiencing is the same problem or something different, and I'll re-open this issue or create a new one as appropriate.
