### ISSUE TITLE
TCP SNI for Kubernetes?

### ISSUE THREAD

**Issue by hapnermw** [linkerd/linkerd#1572] opened 2017-08-09 00:55 UTC
Is there a way to use linkerd-tcp as a k8s ingress controller or the equivalent?

Here's a linkerd-tcp issue with more details.

https://github.com/linkerd/linkerd-tcp/issues/71

**Comment by adleong** [comment] 2017-08-15 20:40
Closed as duplicate of https://github.com/linkerd/linkerd-tcp/issues/71

**Closed by adleong** 2017-08-15 20:40 UTC
