### ISSUE TITLE
Linkerd failed to recover from backpressure

### ISSUE THREAD

**Issue by leozc** [linkerd/linkerd#1227] opened 2017-04-18 19:49 UTC
Architecture:
Version: 0.8.6
ELB_A -> EC2(Ngx -> L5d) -> ELB_B -> EC2(app_svc) -> ELB_C -> EC2(core_svc) -> DB
                                                      ^
                                                      |
                                                   EC2(internal_svc)

L5d talks to namerds which shielded by ELB, and namerd talks to consul

In consul, we use ELB dns as the dest address e.g. /foo resolveds to foo.company.com 

What happened:
We had DB back-pressure which causing downstream app_svc latency spiked (from 10ms -> 6s)

Linkerd failed to deliver traffic to app_svc, even after core_svc and app_svc returned to normal.
The traffic from l5d to ELB_B dropped to 0 for a long period of time (5 mins) and yet internal_svc can deliver traffic to ELB_B

Unfortunately, we couldn't catch the log due all machines were replaced (well :-/) \

Config
```
admin:
  port: 9990

namers:
- kind: io.l5d.fs
  rootDir: disco

routers:
- protocol: http
  label: incoming
  httpAccessLog: /mnt/log/prod_linkerd_access.log
  identifier:
  - kind: io.l5d.path
    segments: 4
    consume: true

  interpreter:
    kind: io.l5d.namerd
    dst: /$/inet/prod-namerd.offerup.net/4100
  servers:
  - port: 4141
    ip: 0.0.0.0
    engine:
      kind: netty4
  client:
    engine:
      kind: netty3
    failureAccrual:
      kind: none

  responseClassifier:
    kind: io.l5d.retryableRead5XX

telemetry:
- kind: io.l5d.commonMetrics
- kind: io.l5d.statsd
  experimental: true
  prefix: l5d_router_prod
  hostname: 127.0.0.1
  port: 8125
  gaugeIntervalMs: 15000
  sampleRate: 0.01
- kind: io.l5d.tracelog
  sampleRate: 0.2
  level: WARNING
```

**Comment by leozc** [comment] 2017-04-18 19:53
Another incident came in while I was writing this up.

Thanks for @klingerf 's help, we shed some light
On  EC2(Ngx -> L5d), I did
```
sudo lsof |grep java  |wc -l
```

and I found we had 200K + file descriptor, it is very likely the root cause.

**Comment by adleong** [comment] 2017-04-24 16:56
Do you think this could be the same file descriptor leak described here: https://github.com/linkerd/linkerd/issues/1235 ?

**Comment by leozc** [comment] 2017-04-24 17:43
Possible - but I didn't catch jvm/fd_count .

**Comment by adleong** [comment] 2017-05-02 23:02
I think it's likely that this is a duplicate of https://github.com/linkerd/linkerd/issues/1256.  Please reopen this issue if you see the problem after using the above fix.

**Closed by adleong** 2017-05-02 23:02 UTC
