### ISSUE TITLE
compiled_protobuf errors on compile

### ISSUE THREAD

**Issue by esbie** [linkerd/linkerd#1182] opened 2017-04-05 20:53 UTC
Occasionally, running `./sbt compile` will fail with compiled protobuf errors.

```
[error] /Users/esbie/workspace/linkerd/mesh/core/target/scala-2.11/src_managed/main/compiled_protobuf/io/linkerd/mesh/resolver.pb.scala:62: Endpoint is already defined as case class Endpoint
[error] case class Endpoint(
[error]            ^
[error] /Users/esbie/workspace/linkerd/mesh/core/target/scala-2.11/src_managed/main/compiled_protobuf/io/linkerd/mesh/resolver.pb.scala:69: Endpoint is already defined as object Endpoint
[error] object Endpoint {
[error]        ^
[error] /Users/esbie/workspace/linkerd/mesh/core/target/scala-2.11/src_managed/main/compiled_protobuf/io/linkerd/mesh/resolver.pb.scala:256: Replicas is already defined as case class Replicas
[error] case class Replicas(
[error]            ^
[error] /Users/esbie/workspace/linkerd/mesh/core/target/scala-2.11/src_managed/main/compiled_protobuf/io/linkerd/mesh/resolver.pb.scala:260: Replicas is already defined as object Replicas
[error] object Replicas {
[error]        ^
[error] /Users/esbie/workspace/linkerd/mesh/core/target/scala-2.11/src_managed/main/compiled_protobuf/io/linkerd/mesh/resolver.pb.scala:542: Resolver is already defined as trait Resolver
[error] trait Resolver {
[error]       ^
[error] /Users/esbie/workspace/linkerd/mesh/core/target/scala-2.11/src_managed/main/compiled_protobuf/io/linkerd/mesh/resolver.pb.scala:547: Resolver is already defined as object Resolver
[error] object Resolver {
[error]        ^
[error] 54 errors found
```

Often `./sbt clean` fixes the issue.

**Comment by klingerf** [comment] 2017-04-05 22:03
Pretty sure this is a dupe of #1108, but seeing as how this one has more info maybe we should close that one.

**Comment by esbie** [comment] 2017-04-05 22:06
arrgh yeah it is... I failed to find #1108 in my search

**Comment by esbie** [comment] 2017-05-08 19:08
I haven't seen this in a while...

**Comment by esbie** [comment] 2017-05-12 17:11
please reopen if this is still an issue

**Comment by adleong** [comment] 2017-05-18 17:40
does anyone have a reliable set of commands to reproduce this?

**Comment by adleong** [comment] 2017-07-06 21:39
This is known annoyingness that only occurs when protobuf changes (or something).
Deleting the compiled scala folder from the `target` directory works around the issue.

**Closed by adleong** 2017-07-06 21:39 UTC
