### ISSUE TITLE
Operation failed with com.twitter.finagle.serverset2.client.KeeperException$NoNode

### ISSUE THREAD

**Issue by dhruvmphatek** [linkerd/linkerd#2078] opened 2018-07-20 11:38 UTC
Continuously printing the message in namerd logs 
Operation failed with com.twitter.finagle.serverset2.client.KeeperException$NoNode

Due to this linkerd Error message is printing on linkerd logs
namerd request failed, Failure(stream closed, flags=0x02) with RemoteInfo -> Upstream Address: Not Available, Upstream id: Not Available, Downstream Address: /192.168.0.165:4180, Downstream label: interpreter/io.l5d.namerd.http.

**Comment by adleong** [comment] 2018-07-23 15:00
Is this a duplicate of #2076?

**Closed** 2018-07-24 05:09 UTC
