### ISSUE TITLE
Linkerd cancels long-lasting grpc requests

### ISSUE THREAD

**Issue by PeterUherek** [linkerd/linkerd#2334] opened 2019-09-30 11:24 UTC
Issue Type:

- [x] Bug report
- [ ] Feature request

**What happened**:
I updated linkerd from the version 1.6.1 to the version 1.6.2 and after that linkerd cancels long-lasting grpc requests ( Request takes 15 seconds ). My client receives grpc cancel code `Error: rpc error: code = Canceled desc = stream terminated by RST_STREAM with error code: CANCEL`. Grpc service does not cancel this call. Client and Service run in go and use grpc v1.24.0 module. 

[The linkerd 1.6.2 changelog](https://github.com/linkerd/linkerd/releases/tag/1.6.2) does not mention anything what can cause this problem. I tried to update linkerd to the latest version, 1.7.0, but there is still same problem. Trace log:

```
 W 0930 10:23:12.838 UTC THREAD28 TraceId:7835fadfedce8425: Exception propagated to the default monitor (upstream address: /10.240.0.5:57834, downstream address: /10.244.3.226:10001, label: #/io.l5d.k8s/prod/grpc/eventhub-inserter-v823). 
 Reset.Cancel 
  
 E 0930 10:23:12.872 UTC THREAD34: [S L:/10.244.4.189:4143 R:/10.240.0.5:57834] dispatcher failed 
 com.twitter.finagle.ChannelClosedException: ChannelException at remote address: /10.240.0.5:57834. Remote Info: Not Available 
 at com.twitter.finagle.netty4.transport.ChannelTransport$$anon$2.channelInactive(ChannelTransport.scala:175) 
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) 
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) 
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) 
 at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) 
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) 
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) 
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) 
 at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) 
 at com.twitter.finagle.netty4.channel.ChannelRequestStatsHandler.channelInactive(ChannelRequestStatsHandler.scala:41) 
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) 
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) 
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) 
 at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) 
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) 
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) 
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) 
 at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:390) 
 at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:355) 
 at io.netty.handler.codec.http2.Http2ConnectionHandler.channelInactive(Http2ConnectionHandler.java:427) 
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) 
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) 
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) 
 at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75) 
 at com.twitter.finagle.netty4.channel.ChannelStatsHandler.channelInactive(ChannelStatsHandler.scala:229) 
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) 
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) 
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) 
 at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:390) 
 at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:355) 
 at io.netty.handler.ssl.SslHandler.channelInactive(SslHandler.java:1050) 
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) 
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) 
 at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224) 
 at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429) 
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) 
 at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231) 
 at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947) 
 at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822) 
 at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) 
 at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) 
 at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:335) 
 at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) 
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) 
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) 
 at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:23) 
 at io.netty.util.concurrent.FastThreadLocalRu
```

**What you expected to happen**:
Linkerd does not throttle long-lasting grpc request

**Environment**:
- linkerd/namerd version, config files: 1.6.2 
- Platform, version, and config files (Kubernetes, DC/OS, etc): Kubernetes v1.14.6
- Cloud provider or hardware configuration: AKS

**Comment by zaharidichev** [comment] 2019-09-30 11:36
@PeterUherek this is an interesting problem. Is there some more information that you can give us. What is happening in the stream. 

Are there data frames being sent consistently. In the last version of linkerd I have done quite a bit of grpc testing and have not noticed  anything like that happening. 
Will try to reproduce the issue and get back to you on that one.

 Meanwhile, do you think you can run linkerd in with debug logging enabled and provide some output to get a better idea of what is really going on? 

Zahari

**Comment by PeterUherek** [comment] 2019-09-30 13:43
I tired to repeated with debug logging but no more logs appeared. 

> Are there data frames being sent consistently.  

Client and service use grpc unary-unary communication. Client sends a one grpc request via linkerd. Service receives and processes request for 30 seconds (There is hard coded sleep for 30 sec to simulate this state). LinkerD returns grpc cancel code after 15 seconds.

**Comment by zaharidichev** [comment] 2019-10-02 14:39
@PeterUherek I think I found where the problem is. If you want, check out the branch from #2337 and see whether that fixes your particular problem. You do not need to put in any special configuration.

**Comment by PeterUherek** [comment] 2019-10-04 08:49
@zaharidichev I deployed linkerd and namerd with your fix to the kubernetes but it does not resolve my problem. The error is still same. Do you need more info?

**Comment by zaharidichev** [comment] 2019-10-04 09:38
Hmmm, this is interesting. Can you show me the exact config that you have for both linkerd and namerd so I can reproduce the situation as close as possible.

I do have a config that reproduces this problem without namerd in place and then the fix resolves it.

**Comment by PeterUherek** [comment] 2019-10-04 09:59
Linkerd config:

```
 config.yaml: |-

   admin:
     ip: 0.0.0.0
     port: 9990

   telemetry:
   - kind: io.l5d.prometheus
   - kind: io.l5d.recentRequests
     sampleRate: 0.25
   - kind: io.l5d.zipkin
     host: linked-svc-mash-zipkin-collector.default.svc.cluster.local
     port: 9410
     sampleRate: 0.01

   usage:
      enabled: false

   routers:
    - protocol: h2
      label: grpc-incoming
      experimental: true
      identifier:
        kind: io.l5d.header.token
        header: grpchost
      interpreter:
        kind: io.l5d.mesh
        dst: /$/inet/namerd-helm.default.svc.cluster.local/4321
        root: /internal
        tls:
          disableValidation: false
          commonName: namerd
          trustCertsBundle: /linkerd/certs/ca.cert.pem
          clientAuth:
            certPath: /linkerd/certs/namerd.cert.pem
            keyPath: /linkerd/certs/namerd.key.pem
        transformers:
        - kind: io.l5d.k8s.localnode
      servers:
      - port: 10005
        ip: 0.0.0.0
        tls:
          certPath: /linkerd/certs/linkerd.cert.pem
          keyPath: /linkerd/certs/linkerd.key.pem
          caCertPath: /linkerd/certs/ca.cert.pem
          requireClientAuth: true

    - protocol: h2
      label: grpc-outgoing
      experimental: true
      identifier:
        kind: io.l5d.header.token
        header: grpchost
      interpreter:
        kind: io.l5d.mesh
        dst: /$/inet/namerd-helm.default.svc.cluster.local/4321
        root: /internal
        tls:
          disableValidation: false
          commonName: namerd
          trustCertsBundle: /linkerd/certs/ca.cert.pem
          clientAuth:
            certPath: /linkerd/certs/namerd.cert.pem
            keyPath: /linkerd/certs/namerd.key.pem
        transformers:
        - kind: io.l5d.k8s.daemonset
          namespace: default
          port: grpc-incoming
          service: linkerd-helm
      servers:
      - port: 10002
        ip: 0.0.0.0
      client:
        tls:
          disableValidation: false
          commonName: linkerd
          trustCertsBundle: /linkerd/certs/ca.cert.pem
          clientAuth:
            certPath: /linkerd/certs/linkerd.cert.pem
            keyPath: /linkerd/certs/linkerd.key.pem

    - protocol: h2
      label: grpc-ingress
      experimental: true
      identifier:
        kind: io.l5d.header.token
        header: grpchost
      interpreter:
        kind: io.l5d.mesh
        dst: /$/inet/namerd-helm.default.svc.cluster.local/4321
        root: /external
        tls:
          disableValidation: false
          commonName: namerd
          trustCertsBundle: /linkerd/certs/ca.cert.pem
          clientAuth:
            certPath: /linkerd/certs/namerd.cert.pem
            keyPath: /linkerd/certs/namerd.key.pem
      servers:
      - port: 4143
        ip: 0.0.0.0
outside of kubernetes cluster
        clearContext: false
        tls:
          certPath: /linkerd/certs/ingress.cert.pem
          keyPath: /linkerd/certs/ingress.key.pem
          requireClientAuth: true
          caCertPath: /linkerd/certs/ingress.ca.pem
```

namerd config:
```
  config.yml: |-
    admin:
      ip: 0.0.0.0
      port: 9991

    namers:
    - kind: io.l5d.k8s
      host: localhost
      port: 8001

    storage:
      kind: io.l5d.k8s
      host: localhost
      port: 8001
      namespace: default

    interfaces:
    - kind: io.l5d.httpController
      ip: 0.0.0.0
      port: 4180
    - kind: io.l5d.mesh
      ip: 0.0.0.0
      port: 4321
      tls:
        certPath: /namerd/certs/namerd.cert.pem
        keyPath: /namerd/certs/namerd.key.pem
        caCertPath: /namerd/certs/ca.cert.pem
        requireClientAuth: true

```

**Comment by zaharidichev** [comment] 2019-10-04 12:35
I see, will try to get to the bottom of it. One question that I have is. Is this l5d to l5d request that is failing. Does both of your server and client have a linkerd proxy running i front of them. Also, I assume the situation does no change when you take namerd out of the equation?

**Comment by PeterUherek** [comment] 2019-10-07 07:42
> One question that I have is. Is this l5d to l5d request that is failing.

It looks like connection between l5d to server is failing. 
> Does both of your server and client have a linkerd proxy running i front of them.

Yes, client and server have linkerd proxy running in front of them.
> I assume the situation does no change when you take namerd out of the equation?

Yes, It does not change.

**Comment by zaharidichev** [comment] 2019-10-07 10:19
@PeterUherek I think I found where the problem is and decided to take a different approach. You can check out the same branch and try it out. What you need to do however is to specify a failureThreshold config for your client and server configs as the default now is 5 seconds I think. 

so you need to have something like: 

```

**Comment by PeterUherek** [comment] 2019-10-07 15:49
It helps.  Thank you. 

Why is not the `failureThreshold ` parameter in the documentation? It is missing in the router[ client section](https://api.linkerd.io/1.7.0/linkerd/index.html#client-parameters) and also in the [server section](https://api.linkerd.io/1.7.0/linkerd/index.html#server-parameters).

**Comment by zaharidichev** [comment] 2019-10-07 17:26
So yes, I actually just exposed this conf parameter in this branch so its not in the latest release yet. Once this pr gets merged (hopefully) and we release a new version it will be present in the docs.

**Comment by adleong** [comment] 2019-10-09 16:49
@PeterUherek I wanted to give you some additional context for what is going on here and try to understand your service better.  Linkerd uses a failure detector which will periodically send HTTP/2 PINGs to the server to keep the connection active and to make sure the server is still alive.  What seems to be happening here is that while your server is sleeping, Linkerd notices that it is not responding and closes the connection.

Is it necessary for your server to sleep and stop responding to PINGs?  What happens if your server receives more than one message concurrently?  If the server stops responding entirely while a request is being processed, that seems like a serious flaw in the server's HTTP/2 implementation.

To be clear, I don't think there's anything inherently wrong with @zaharidichev's change to expose failure threshold configuration, but I wanted to understand your problem better before giving users more ways to shoot themselves in the foot.  In this case, I think the failure detector is doing its job correctly.

**Comment by adleong** [comment] 2019-11-05 18:00
Closing due to inactivity

**Closed by adleong** 2019-11-05 18:00 UTC
