### ISSUE TITLE
Investigating using OpenJ9 JVM

### ISSUE THREAD

**Issue by adleong** [linkerd/linkerd#1881] opened 2018-03-29 21:02 UTC
[OpenJ9](https://www.eclipse.org/openj9/) is a JVM optimized for the cloud.  We should evaluate if Linkerd can be run on it and if there are any tangible benefits such as lower memory footprint, faster startup time, or better throughput.

**Comment by adleong** [comment] 2018-04-06 18:59
Finagle has a dependency on the Hotspot JVM: https://github.com/twitter/util/blob/develop/util-jvm/src/main/scala/com/twitter/jvm/Jvm.scala#L262

When Linkerd is started on the OpenJ9 JVM, the following error is thrown:

```
java.lang.UnsatisfiedLinkError: sun/management/VMManagementImpl.getVersion0()Ljava/lang/String;
	at sun.management.VMManagementImpl.<clinit>(VMManagementImpl.java:64)
	at sun.management.ManagementFactoryHelper.<clinit>(ManagementFactoryHelper.java:455)
	at java.lang.Class.forNameImpl(Native Method)
	at java.lang.Class.forName(Class.java:297)
	at com.twitter.jvm.Hotspot.liftedTree1$1(Hotspot.scala:37)
	at com.twitter.jvm.Hotspot.<init>(Hotspot.scala:31)
	at com.twitter.jvm.Jvm$.liftedTree2$1(Jvm.scala:262)
	at com.twitter.jvm.Jvm$._jvm$lzycompute(Jvm.scala:262)
	at com.twitter.jvm.Jvm$._jvm(Jvm.scala:261)
	at com.twitter.jvm.Jvm$.apply(Jvm.scala:274)
	at com.twitter.jvm.JvmStats$.register(JvmStats.scala:98)
	at com.twitter.finagle.Init$.<init>(Init.scala:46)
	at com.twitter.finagle.Init$.<clinit>(Init.scala)
	at com.twitter.finagle.client.StackClient$.endpointStack(StackClient.scala:58)
	at com.twitter.finagle.client.StackClient$.newStack(StackClient.scala:224)
	at com.twitter.finagle.buoyant.H2$Client$.<init>(H2.scala:28)
	at com.twitter.finagle.buoyant.H2$Client$.<clinit>(H2.scala)
	at io.buoyant.router.H2$Router$.<init>(H2.scala:49)
	at io.buoyant.router.H2$Router$.<clinit>(H2.scala)
	at io.buoyant.router.H2$.<init>(H2.scala:77)
	at io.buoyant.router.H2$.<clinit>(H2.scala)
	at io.buoyant.linkerd.protocol.H2Initializer.<init>(H2Config.scala:40)
	at java.lang.J9VMInternals.newInstanceImpl(Native Method)
	at java.lang.Class.newInstance(Class.java:1773)
	at com.twitter.app.LoadService$.$anonfun$apply$7(LoadService.scala:73)
	at com.twitter.app.LoadService$$$Lambda$81.00000000CC7244F0.apply(Unknown Source)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$Lambda$24.00000000CC587E30.apply(Unknown Source)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:52)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:241)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:238)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
	at com.twitter.app.LoadService$.apply(LoadService.scala:62)
	at com.twitter.finagle.util.LoadService$.apply(LoadService.scala:14)
	at io.buoyant.linkerd.Linker$.LoadedInitializers$lzycompute(Linker.scala:65)
	at io.buoyant.linkerd.Linker$.LoadedInitializers(Linker.scala:64)
	at io.buoyant.linkerd.Linker$.parse$default$2(Linker.scala:79)
	at io.buoyant.linkerd.Main$.loadLinker(Main.scala:69)
	at io.buoyant.linkerd.Main$.main(Main.scala:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.twitter.app.App.$anonfun$nonExitingMain$3(App.scala:233)
	at com.twitter.app.App$$Lambda$178.00000000CCBD6FA0.apply(Unknown Source)
	at scala.Option.foreach(Option.scala:257)
	at com.twitter.app.App.nonExitingMain(App.scala:232)
	at com.twitter.app.App.nonExitingMain$(App.scala:210)
	at io.buoyant.linkerd.Main$.nonExitingMain(Main.scala:20)
	at com.twitter.app.App.main(App.scala:198)
	at com.twitter.app.App.main$(App.scala:196)
	at io.buoyant.linkerd.Main$.main(Main.scala:20)
	at io.buoyant.linkerd.Main.main(Main.scala)
Exception thrown in main on startup
```

Support for the OpenJ9 would need to be added to twitter-util to have this work.  Or, at the very least, Finagle should not crash on an unknown jvm and should instead just be missing jvm stats.

**Comment by wmorgan** [comment] 2018-06-27 18:37
Have a report from a customer that they've successfully used this in production and see noticeably reduced memory footprint and startup times. Let's bump this up the priority queue.

**Comment by dadjeibaah** [comment] 2018-07-10 17:38
Since Linkerd is built on Finagle, work is needed to ensure the J9 JVM works with Finagle. Unfortunately, Finagle is dependent on some features present in the Hotspot JVM. This causes an `UnsatisfiedLinkerdError` when attempting to run Linkerd with OpenJ9. The issue is fixed by this [PR](https://github.com/twitter/util/pull/218). Until this PR is merged into twitter-util, you will need to build twitter-util from it’s Github source code.

## Building Linkerd with OpenJ9.

- Fork and clone [twitter-util](https://github.com/twitter/util), [finagle](https://github.com/twitter/finagle), [twitter-server](https://github.com/twitter/twitter-server) from the Twitter OSS repo on Github
- Make the changes similar to this PR in twitter-util.
- Build and publish the Twitter OSS libraries to your local environment by using dodo with this command `./dodo/bin/build --no-test finagle`
- Just to be safe, cd into the twitter-util repo and run `./sbt publishLocal` to make sure the changes you made are placed in your local cache.
- Go into the Linkerd repo and build a linkerd docker image with the base image as the `adoptopenjdk openj9` image.
  - `./sbt 'set Base.dockerJavaImage in (linkerd, Bundle) := "adoptopenjdk/openjdk8-openj9:jdk8u162-b12_openj9-0.8.0"' linkerd/docker`


## Comparing vanilla Linkerd 1.4.3 and Linkerd 1.4.3+OpenJ9

The OpenJ9 indeed has significant improvements in memory footprint. We run a simple hello world service with slow_cooker sending 500 qps to Linkerd in docker. Using `top`, we see that Linkerd 1.4.3 uses ~ 200MB.

<img width="562" alt="screen shot 2018-07-09 at 8 18 21 pm" src="https://user-images.githubusercontent.com/2197104/42527169-c64b6fe8-842c-11e8-9083-80b5ee79f70d.png">

Linkerd 1.4.3 with OpenJ9 memory footprint shows

<img width="593" alt="screen shot 2018-07-09 at 8 28 01 pm" src="https://user-images.githubusercontent.com/2197104/42527185-ca0fc7d2-842c-11e8-8925-7be3636cc080.png">

Pretty cool! That’s almost half the size in memory!

## Fast and the Furious: Vanilla JDK vs OpenJ9

Next, we test out the startup time for the J9 JVM to see if we do gain a performance improvement. Since Linkerd starts up and does not exit, it’s a going to be a little tricky testing out how fast Linkerd starts up with J9. The method used is a little hacky however, it does provide us some sense of how fast the two JVMs are. Here is how we tested it:

- We first set up a curl loop to poll the admin/ping endpoint every second like so:
  - `while sleep 1; do curl  http://localhost:<admin_port>/admin/ping; done`
- We run linkerd from in a docker environment
- We wait to see how long Linkerd responds with a “pong” message. You will see three different `curl`
  messages when running the test. Initially, you should see:
- `Failed to connect to localhost port 9991: Connection refused`
    - The Linkerd container isn’t up yet.
- `Empty reply from server`
    -   Linkerd is in the process of initializing
- `pong`
   - Linkerd is is fully initialized.

The results are determined by a pretty easy albeit rudimentary way by counting the number of “Empty reply from server” we get before receiving “pong”.  Since each message is displayed every second, we can get an idea, in seconds, of how long it takes for Linkerd to startup with both JVMs.

With the vanilla Linkerd we get about 30 x “Empty reply from server” messages which equate to roughly about 30 seconds. With OpenJ9 it takes about 10 x “Empty reply from server” = 10 seconds!. That’s like a 60% increase in startup speed. Crazy! I think the vanilla JDK owes OpenJ9 a 10 second car.

**Comment by flatmap13** [comment] 2018-07-10 19:01
@dadjeibaah Thanks for conducting these experiments, your findings are in line with our results :)

**Comment by dadjeibaah** [comment] 2018-07-10 21:11
That's great to hear! I think the next steps for this is to see if we can squeeze more out of the JVM. I found out there are various flags that can be used with J9 like `-Xquickstart` and enabling AOT. It would be good to also get some benchmarks to see what we are working with.

**Comment by dadjeibaah** [comment] 2018-07-11 16:58
@leozc, Linkerd is configured to use the CMS GC.

**Comment by dadjeibaah** [comment] 2018-07-13 00:53
If folks would like to try out Linkerd+OpenJ9, there is a docker image available at Buoyant's [docker repo](https://hub.docker.com/r/buoyantio/linkerd/tags/) with the image tag `1.4.3-SNAPSHOT-jdk-openj9`. It'd be interesting to see experiment results from the community. Also, experimental Linkerd+OpenJ9 docker images will be available in upcoming Linkerd releases. This should make it easy to include the new build artifact in your test environments.

**Closed** 2018-07-16 22:39 UTC
