### ISSUE TITLE
Enable telemetry for Namerd

### ISSUE THREAD

**Issue by Ashald** [linkerd/linkerd#1207] opened 2017-04-13 18:10 UTC
> i don’t think namerd supports telemeters yet, but it should

(c) @olix0r 

I don't think any other details needed. :)

**Comment by adleong** [comment] 2017-05-03 18:03
We should do this soon.

**Comment by adleong** [comment] 2017-05-05 21:57
Closing as duplicate of #740.  But yes, we should still do this soon.

**Closed by adleong** 2017-05-05 21:57 UTC
Labels: help wanted, namerd
