### ISSUE TITLE
Memory leak - when invoking non-existing service under a heavy load

### ISSUE THREAD

**Issue by MirzaMerdovic** [linkerd/linkerd#1824] opened 2018-02-19 10:07 UTC
Issue Type:

- [X] Bug report
- [ ] Feature request

**What happened**:
The gRPC service names got changed, while load tests were running this caused linkerd to produce a memory leak.

**What you expected to happen**:
linkerd memory consumption shouldn't be affected, since linkerd is aware that it received a request for a non-existing service name.

`linkerd_1  | I 0216 14:36:44.672 UTC THREAD29: no available endpoints
linkerd_1  | com.twitter.finagle.NoBrokersAvailableException: No hosts are available for /svc/xxx-grpcservice, Dtab.base=[/svc=>/#/io.l5d.consul/dc1], Dtab.local=[]. Remote Info: Not Available`

**How to reproduce it (as minimally and precisely as possible)**:
We were load testing our gRPC services through linkerd. Our test suite is xUnit 2.3.1 (.net core) and we ran 8-12 test scenarios in parallel. Test scenarios were basically invoking tests consecutively in specified time range (e.g. 2 hours) we no or some delay between two service calls.
[Code example](https://github.com/linkerd/linkerd/files/1736134/LoadTestExample.txt) that hopefully might help.
Each test scenario creates one gRPC channel.

**Anything else we need to know?**:
When we run our tests with correct service names the memory consuption is fine without increases.
Uploded linkerd configuration has retrying turned off, but the same thing happens with it turned on; we just wanted to see if turning it off might change something.

**Environment**:
- linkerd version, config files: buoyantio/linkerd:1.3.5 (buoyantio/linkerd:1.3.3)
- Platform, version, and config files (Kubernetes, DC/OS, etc): docker container with Ubuntu linux
[docker-compose.yaml](https://github.com/linkerd/linkerd/files/1736036/docker-compose.txt)
[linkerd.yaml](https://github.com/linkerd/linkerd/files/1736039/linkerd.txt)
- Cloud provider or hardware configuration: OS: Windows 10 Enterprise x64; processoer: Intel E3-1505M v5 @ 2.8Ghz (8 cpus); RAM: 32 GB

**Comment by wmorgan** [comment] 2018-02-19 22:00
Thanks for the report, @MirzaMerdovic!

**Comment by chrisgoffinet** [comment] 2018-05-20 23:44
Confirmed the consul memory leak looks to be due to `LookupCache` having its own `consulApi` being passed to. As soon as the non-existent svcs  get torn down after idleTimeout of 10m, the connections are released. /cc @adleong 

We should make the code use a pool of consul agents for requests.

**Comment by adleong** [comment] 2018-05-22 01:29
Thank you for investigating this @chrisgoffinet!

It sounds like Linkerd is getting many requests for many different service names.  There is a memory cost associated with each service that Linkerd maintains, even if the service cannot successfully route requests.  It is a design decision that Linkerd treat these services as valid because of the dynamic nature of binding.

For example, consider the service name `/svc/foo` and the dtab `/svc => /#/io.l5d.consul/dc1`.  If `foo` does not exist in consul, this request will fail.  However, Linkerd will keep the `/svc/foo` service because `foo` might be created in consul at a later date.  Or the dtab might be update to point `/svc/foo` at a destination that does exist.  

There are a couple of things that you can do to mitigate the memory cost of keeping all of these services.

1. You can try reducing the size of Linkerd's path cache: https://linkerd.io/config/head/linkerd/index.html#binding-cache  This will reduce the maximum number of services that Linkerd will keep cached.  Reducing this number too much can hurt Linkerd performance when Linkerd is connecting to many different valid services, but as long it is larger than the total number of valid services that you expect Linkerd to talk to, it should be okay.
2. You can try reducing the idleTtlSecs timeout: https://linkerd.io/config/head/linkerd/index.html#binding-cache  This reduces the amount of time Linkerd waits before closing idle services.  With a smaller number, Linkerd will more quickly close the idle invalid services.  However, there is a performance cost if this is shorter than the idle times between requests for valid services.

**Comment by adleong** [comment] 2018-05-22 01:33
The consul connection leak is very similar to the service leak I described above.  When Linkerd attempts to resolve a name in consul, it establishes a watch on that name, even if the service does not currently exist.  This allows Linkerd to be notified immediately in case a service with that name is created.  The result is that Linkerd maintains a connection to Consul per name it is watching.  

This can be mitigated with the same techniques as above:

1. Limiting the size of the client cache: https://linkerd.io/config/head/linkerd/index.html#binding-cache This will put a limit on the number of clients that Linkerd will cache and therefore put a limit on the number of connections to consul Linkerd will maintain.
2. Reducing the idleTtlSecs timeout: https://linkerd.io/config/head/linkerd/index.html#binding-cache will cause Linked to tear down watches on idle names more quickly.

**Comment by adleong** [comment] 2018-05-22 01:35
@MirzaMerdovic @chrisgoffinet Let me know if my explanation makes sense and if it is consistent with your observations.  I also encourage you to experiment with the configuration options above and let me know if is sufficient to get memory/connections/performance to an acceptable level.

**Comment by MirzaMerdovic** [comment] 2018-05-22 14:30
@adleong Thanks for detailed information and @chrisgoffinet thanks for investigating this one.
@adleong I have one question you said here: 
> The result is that Linkerd maintains a connection to Consul per name it is watching.

So if I have thousands of requests towards the non-existing service Linkerd will cache 1 entry not thousands? In our load test we invoked 1-6 gRPC services, sorry if I got this all wrong.

**Comment by adleong** [comment] 2018-05-22 21:12
@MirzaMerdovic That's correct.  Linkerd should maintain one connection to Consul per service that is watching (regardless of if that service exists or not).  It should be independent of the number of requests.  If you are seeing new connections for each request to the same service, that is a bug.

**Comment by MirzaMerdovic** [comment] 2018-05-23 07:00
@adleong Number of connection is consistent to the number of channels created, so there wasn't a problem there and there weren't many different service names in the play. 
What I don't understand is why ins scenario where linkerd invokes the same service and than when we change the service name while the linkerd still invokes the service by the old name (name that doesn't exist anymore) memory consumption grows. @chrisgoffinet explanation made sense to me, so can I asume the Consul is a culprit here?

This is not something that is blocking us in our work, and I don't find it as a serious issue since it probably won'r happen again and if it does it's easy to mitigate, but I am just curios to understand why is it happening.

**Comment by chrisgoffinet** [comment] 2018-05-23 16:37
@mirosval the memory growth is coming from the fact that they create a ton of stats for every new service that tries to be requested. So for example if you are sending services with the following:

`helloworld.Greeter-44c56e49-b192-4272-9148-7a2fc698b0b4` it creates stats:

```/grpc-consul/service/svc/helloworld.Greeter-44c56e49-b192-4272-9148-7a2fc698b0b4/failures" : 1,
  "rt//grpc-consul/service/svc/helloworld.Greeter-44c56e49-b192-4272-9148-7a2fc698b0b4/failures/com.twitter.finagle.NoBrokersAvailableException" : 1,
  "rt//grpc-consul/service/svc/helloworld.Greeter-44c56e49-b192-4272-9148-7a2fc698b0b4/request/stream/data_bytes.count" : 0,
  "rt//grpc-consul/service/svc/helloworld.Greeter-44c56e49-b192-4272-9148-7a2fc698b0b4/request/stream/stream_duration_ms.count" : 0,
  "rt//grpc-consul/service/svc/helloworld.Greeter-44c56e49-b192-4272-9148-7a2fc698b0b4/request/stream/stream_failures" : 0,
  "rt//grpc-consul/service/svc/helloworld.Greeter-44c56e49-b192-4272-9148-7a2fc698b0b4/request/stream/stream_success" : 0,
  "rt//grpc-consul/service/svc/helloworld.Greeter-44c56e49-b192-4272-9148-7a2fc698b0b4/request_latency_ms.count" : 0,
  "rt//grpc-consul/service/svc/helloworld.Greeter-44c56e49-b192-4272-9148-7a2fc698b0b4/requests" : 1,
  "rt//grpc-consul/service/svc/helloworld.Greeter-44c56e49-b192-4272-9148-7a2fc698b0b4/response/stream/data_bytes.count" : 0,
  "rt//grpc-consul/service/svc/helloworld.Greeter-44c56e49-b192-4272-9148-7a2fc698b0b4/response/stream/stream_duration_ms.count" : 0,
  "rt//grpc-consul/service/svc/helloworld.Greeter-44c56e49-b192-4272-9148-7a2fc698b0b4/response/stream/stream_failures" : 0,
  "rt//grpc-consul/service/svc/helloworld.Greeter-44c56e49-b192-4272-9148-7a2fc698b0b4/response/stream/stream_success" : 0,
  "rt//grpc-consul/service/svc/helloworld.Greeter-44c56e49-b192-4272-9148-7a2fc698b0b4/retries/backoffs_exhausted" : 0,
  "rt//grpc-consul/service/svc/helloworld.Greeter-44c56e49-b192-4272-9148-7a2fc698b0b4/retries/budget" : 0.0,
  "rt//grpc-consul/service/svc/helloworld.Greeter-44c56e49-b192-4272-9148-7a2fc698b0b4/retries/budget_exhausted" : 0,
  "rt//grpc-consul/service/svc/helloworld.Greeter-44c56e49-b192-4272-9148-7a2fc698b0b4/retries/classification_timeout" : 0,
  "rt//grpc-consul/service/svc/helloworld.Greeter-44c56e49-b192-4272-9148-7a2fc698b0b4/retries/per_request.count" : 0,
  "rt//grpc-consul/service/svc/helloworld.Greeter-44c56e49-b192-4272-9148-7a2fc698b0b4/retries/request_stream_too_long" : 0,
  "rt//grpc-consul/service/svc/helloworld.Greeter-44c56e49-b192-4272-9148-7a2fc698b0b4/retries/response_stream_too_long" : 0,
  "rt//grpc-consul/service/svc/helloworld.Greeter-44c56e49-b192-4272-9148-7a2fc698b0b4/retries/total" : 0,
  "rt//grpc-consul/service/svc/helloworld.Greeter-44c56e49-b192-4272-9148-7a2fc698b0b4/sourcedfailures//svc/helloworld.Greeter-44c56e49-b192-4272-9148-7a2fc698b0b4" : 1,
  "rt//grpc-consul/service/svc/helloworld.Greeter-44c56e49-b192-4272-9148-7a2fc698b0b4/sourcedfailures//svc/helloworld.Greeter-44c56e49-b192-4272-9148-7a2fc698b0b4/com.twitter.finagle.NoBrokersAvailableException" : 1,
  "rt//grpc-consul/service/svc/helloworld.Greeter-44c56e49-b192-4272-9148-7a2fc698b0b4/stream/data_bytes.count" : 0,
  "rt//grpc-consul/service/svc/helloworld.Greeter-44c56e49-b192-4272-9148-7a2fc698b0b4/stream/stream_failures" : 0,
  "rt//grpc-consul/service/svc/helloworld.Greeter-44c56e49-b192-4272-9148-7a2fc698b0b4/stream/stream_success" : 0,
  "rt//grpc-consul/service/svc/helloworld.Greeter-44c56e49-b192-4272-9148-7a2fc698b0b4/stream/total_latency_ms.count" : 0,
  "rt//grpc-consul/service/svc/helloworld.Greeter-44c56e49-b192-4272-9148-7a2fc698b0b4/success" : 0
```

And on top of the new stats for every service that is requested, it also makes connections to Consul.

When you run your unit tests, make a curl call to the admin port for `/admin/metrics.json?pretty=1` and you can see the tons of stats that end up getting created for services that do not exist. This adds to the memory growth that is seen.

**Comment by MirzaMerdovic** [comment] 2018-05-23 18:22
@chrisgoffinet thanks for the clarification!

**Comment by wmorgan** [comment] 2018-05-24 01:18
So is this effectively "working as intended", or is there an underlying bug that has been uncovered?

**Comment by chrisgoffinet** [comment] 2018-05-24 01:58
I would say yes after all the clarifications and design decisions being made here.


Best,
Chris On Wed, May 23, 2018 at 9:18pm, William Morgan < notifications@github.com [notifications@github.com] > wrote:
So is this effectively "working as intended", or is there an underlying bug that has been uncovered?

**Closed** 2018-05-30 20:36 UTC
