### ISSUE TITLE
Suspected slow leak for Linkerd 1.1.2

### ISSUE THREAD

**Issue by leozc** [linkerd/linkerd#1615] opened 2017-08-30 02:53 UTC
Issue Type:

- [X ] Bug report
- [ ] Feature request

**What happened**:
We are observing gradual CPU usage climb after l5d running after 3+ days - and the machine eventually reached to 100% CPU and got terminated by auto scaling group.

Restarting L5d process and everything can return to normal which is good for another 3+ days…

Did heap/metrics/lint/yourkit dumps, sent to olix0r.

Note I have disabled everything in telemetry, which was suspected the source of the issue previously.

**What you expected to happen**:
Linkerd process should not cause CPU usage increase gradually.

**How to reproduce it (as minimally and precisely as possible)**:
This can only be reproduced in production workload, and put the box for 3 -4 days.
Each Second the L5d process services around 700+ requests/s

**Anything else we need to know?**:

**Environment**:
AWS 
ubuntu 14.04 
```
uname -r
3.13.0-121-generic
```
The dump and snapshot sent should have all the necessary information.
Here are the JVM ARGS
JVM_OPTIONS='-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=true -Dcom.sun.management.jmxremote.password.file=/opt/jmx.pass -Dcom.sun.management.jmxremote.port=1098 -Dsun.net.inetaddr.ttl=30 -Djava.net.preferIPv4Stack=true  -Xms2g -Xmx2g -Dsun.net.inetaddr.ttl=60 -XX:+AggressiveOpts -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:+CMSClassUnloadingEnabled  -XX:+ScavengeBeforeFullGC -XX:+CMSScavengeBeforeRemark -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=70 -XX:-TieredCompilation -XX:+UseStringDeduplication  -Dcom.twitter.util.events.sinkEnabled=false -XX:+PrintGCApplicationStoppedTime -XX:+PrintGCDateStamps -verbose:gc -XX:+PrintGCDetails -Xloggc:/mnt/log/linkerd-gc.log -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=512M'

Related issues:
https://discourse.linkerd.io/t/suspected-slow-leak-for-linkerd-1-1-2/226/3

Mentioned By:
https://github.com/linkerd/linkerd/pull/1600
<img width="1705" alt="screen shot 2017-08-17 at 9 18 36 am" src="https://user-images.githubusercontent.com/1513416/29853355-5bd2987e-8cf4-11e7-932e-460185c583b9.png">
<img width="1704" alt="screen shot 2017-08-17 at 11 48 59 am" src="https://user-images.githubusercontent.com/1513416/29853360-64d264c2-8cf4-11e7-84d9-2c87d14cd227.png">

**Comment by hawkw** [comment] 2017-09-01 19:29
I've spent some time with the GC logs in the dumps @leozc gave us, and I can say with some certainty that it's not GC-related.

**Comment by hawkw** [comment] 2017-09-05 19:53
Closing this as I've talked it over with @leozc a bit and it appears that the issue is caused by interaction with a custom plugin – none of the data we have indicates a bug in Linkerd.

**Closed by hawkw** 2017-09-05 19:53 UTC
Labels: bug
