### ISSUE TITLE
IllegalArgumentException thrown in downstream Linkerd when a lot of data is being transferred

### ISSUE THREAD

**Issue by mebe** [linkerd/linkerd#1844] opened 2018-03-02 14:39 UTC
Issue Type:

- [X] Bug report
- [ ] Feature request

**What happened**:

Downstream Linkerd throws 

```
java.lang.IllegalArgumentException: invalid message 'DefaultHttpContent(data: UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 0, widx: 8192, cap: 8192/8192), decoderResult: success)'
```

**What you expected to happen**:

No error is thrown.

**How to reproduce it (as minimally and precisely as possible)**:

I haven't been able to compose a good reproduction for this. We are seeing this when we run a linker-to-linker setup in front of an object storage system. This error happens in the downstream Linkerd's running on the storage nodes.

The way we've been encountering this is by running [COSBench](https://github.com/intel-cloud/cosbench) through the Linkerd's to our object storage. There is no precise timescale or data amounts I can give for when this error starts happening.

**Full stack trace**:

```
java.lang.IllegalArgumentException: invalid message 'DefaultHttpContent(data: UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 0, widx: 8192, cap: 8192/8192), decoderResult: success)'
	at com.twitter.finagle.netty4.http.Netty4ClientStreamTransport.$anonfun$read$3(StreamTransports.scala:192)
	at com.twitter.util.Future.$anonfun$flatMap$1(Future.scala:1740)
	at com.twitter.util.Promise$Transformer.liftedTree1$1(Promise.scala:228)
	at com.twitter.util.Promise$Transformer.k(Promise.scala:228)
	at com.twitter.util.Promise$Transformer.apply(Promise.scala:239)
	at com.twitter.util.Promise$Transformer.apply(Promise.scala:220)
	at com.twitter.util.Promise$$anon$7.run(Promise.scala:532)
	at com.twitter.concurrent.LocalScheduler$Activation.run(Scheduler.scala:198)
	at com.twitter.concurrent.LocalScheduler$Activation.submit(Scheduler.scala:157)
	at com.twitter.concurrent.LocalScheduler.submit(Scheduler.scala:274)
	at com.twitter.concurrent.Scheduler$.submit(Scheduler.scala:109)
	at com.twitter.util.Promise.runq(Promise.scala:522)
	at com.twitter.util.Promise.updateIfEmpty(Promise.scala:887)
	at com.twitter.util.Promise.update(Promise.scala:859)
	at com.twitter.util.Promise.setValue(Promise.scala:835)
	at com.twitter.concurrent.AsyncQueue.offer(AsyncQueue.scala:122)
	at com.twitter.finagle.netty4.transport.ChannelTransport$$anon$1.channelRead(ChannelTransport.scala:183)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at com.twitter.finagle.netty4.channel.ChannelRequestStatsHandler.channelRead(ChannelRequestStatsHandler.scala:41)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at com.twitter.finagle.netty4.http.handler.UnpoolHttpHandler$.channelRead(UnpoolHttpHandler.scala:32)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at com.twitter.finagle.netty4.http.handler.BadRequestHandler$.channelRead0(BadRequestHandler.scala:23)
	at com.twitter.finagle.netty4.http.handler.BadRequestHandler$.channelRead0(BadRequestHandler.scala:20)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at io.netty.handler.codec.http.HttpServerExpectContinueHandler.channelRead(HttpServerExpectContinueHandler.java:95)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at com.twitter.finagle.netty4.http.handler.PayloadSizeHandler.channelRead(PayloadSizeHandler.scala:59)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
	at com.twitter.finagle.netty4.channel.ChannelStatsHandler.channelRead(ChannelStatsHandler.scala:106)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1342)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:934)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at com.twitter.finagle.util.BlockingTimeTrackingThreadFactory$$anon$1.run(BlockingTimeTrackingThreadFactory.scala:23)
	at java.lang.Thread.run(Thread.java:748)
```

**Environment**:
- Linkerd version: 1.3.5
- Linkerd JVM settings:
  - Compute node: `LOCAL_JVM_OPTIONS="-XX:MaxDirectMemorySize=2G" JVM_HEAP_MIN=4G JVM_HEAP_MAX=4G`
  - Storage nodes: `LOCAL_JVM_OPTIONS="-XX:MaxDirectMemorySize=2G" JVM_HEAP_MIN=1G JVM_HEAP_MAX=1G`
- Config files:
  - Compute node:

```
admin:
  port: 9990

routers:
- protocol: http
  dtab: |
    /storage1 => /$/inet/storage1/6007;
    /storage2 => /$/inet/storage2/6007;
    /storage3 => /$/inet/storage3/6007;
    /storage4 => /$/inet/storage4/6007;
    /storage => /storage1 & /storage2 & /storage3 & /storage4;
    /svc/storage => /storage;
  httpAccessLog: logs/access.log
  maxRequestKB: 51200
  maxResponseKB: 51200
  servers:
  - port: 6007
    ip: 127.0.0.1
  client:
    loadBalancer:
      kind: ewma
```
  - Storage nodes:

```
admin:
  port: 9990

routers:
- protocol: http
  dtab: |
    /svc/storage => /$/inet/127.0.0.1/6007;
  httpAccessLog: logs/access.log
  label: storage1
  maxRequestKB: 51200
  maxResponseKB: 51200
  servers:
  - port: 6007
    ip: 10.0.0.1
```

- Platform: bare metal, CentOS 7
- Hardware configuration: Dell R930 for compute and Dell R730XD's for storage with plenty of resources

- Cosbench workload config:

```
<?xml version="1.0" encoding="UTF-8" ?>
<workload name="planning-cloud-v1-linkerd" description="Simulates multiple planning cloud instances.">
 
  <storage type="s3" config="accesskey=a;secretkey=b;endpoint=http://openio;proxyhost=127.0.0.1;proxyport=6007;path_style_access=true" />
 
  <workflow>
 
    <workstage name="init">
      <work type="init" workers="1" config="containers=r(2,2)" />
    </workstage>
 
    <workstage name="prepare">
      <work type="prepare" workers="1" config="hashCheck=true;containers=r(2,2);objects=r(1,30);sizes=h(1|1|11267,1|2|378,2|4|210,4|8|212,8|16|178,16|32|587,32|64|1528,64|128|285446,128|256|410638,256|512|26416,512|1024|1093,1024|2048|996,2048|4096|830,4096|8192|1125,8192|16384|845,16384|32768|677,32768|51199|417,51200|51200|103366)KB" />
    </workstage>
 
    <workstage name="main">
      <work name="main" workers="100" runtime="600">
        <operation type="read" ratio="50" config="hashCheck=true;containers=u(2,2);objects=u(1,30)" />
        <operation type="write" ratio="50" config="hashCheck=true;containers=u(2,2);objects=u(31,60);sizes=h(1|1|11267,1|2|378,2|4|210,4|8|212,8|16|178,16|32|587,32|64|1528,64|128|285446,128|256|410638,256|512|26416,512|1024|1093,1024|2048|996,2048|4096|830,4096|8192|1125,8192|16384|845,16384|32768|677,32768|51199|417,51200|51200|103366)KB" />
      </work>
    </workstage>
 
    <workstage name="cleanup">
      <work type="cleanup" workers="1" config="containers=r(2,2);objects=r(1,60)" />
    </workstage>
 
    <workstage name="dispose">
      <work type="dispose" workers="1" config="containers=r(2,2)" />
    </workstage>
 
  </workflow>
 
</workload>
```

**Comment by wmorgan** [comment] 2018-03-03 02:13
Thanks for filling this. We'll take a look!

**Comment by adleong** [comment] 2018-03-20 22:02
Hi @mebe, can you provide some more information about the severity and impact of this error?  Do you see failed requests from the client's (COSBench) perspective?  Approximately what percentage of requests fail?  Does Linkerd seem to be handling all other requests correctly, or does this exception seem to put Linkerd into a degraded or failing state?  Are the requests that fail safe to retry?

**Comment by mebe** [comment] 2018-03-21 11:54
@adleong,

We are being blocked by #1690 for the object storage use case. After that issue has been resolved, we'll dive deeper into this one.

Thanks!

**Comment by chrisgoffinet** [comment] 2018-04-11 19:49
Haven't been able to reproduce this just yet. So far I've setup the environment where I randomly send `SIGSTOP` and `SIGCONT` to the compute (linkerd) process, and I've also setup chaos monkey style approach of randomly killing that process. So far none have yielded the result. My next step is to try simulating packet corruption.

**Comment by adleong** [comment] 2018-04-24 20:39
@chrisgoffinet have you had any success in reproducing this issue?

**Comment by adleong** [comment] 2018-05-08 20:43
@mebe Closing this for now, please reopen it if you see this issue again.

**Comment by chris-goffinet-ck** [comment] 2018-05-22 01:02
Let's reopen this, I am finding this in Credit Karma logs too. I'm gonna try reproducing this more.

**Comment by adleong** [comment] 2018-05-30 20:36
@chris-goffinet-ck any update here?

**Comment by adleong** [comment] 2018-06-19 20:44
@chris-goffinet-ck I know you're still investigating this one but I'm going to close it for now because it's not actionable until we have more information.  Please re-open when you have more to share.

**Closed by adleong** 2018-06-19 20:44 UTC

**Comment by zackangelo** [comment] 2019-09-24 20:48
Just wanted to mention that we're also seeing this error in our logs. Not sure what's causing it yet either but will post when/if we obtain more info.

**Comment by zaharidichev** [comment] 2019-09-25 08:04
@zackangelo whenever you have more info around the setup that you see this occuring with, let us know. Will take a look
