### ISSUE TITLE
l5d pod fails to proxy requests after a period of time

### ISSUE THREAD

**Issue by betson-nuovo** [linkerd/linkerd#1971] opened 2018-06-04 22:36 UTC
Issue Type:
Bug report

**What happened**: 
One or more l5d pods in a k8s cluster eventually enter a state where certain types of requests consistently return a 502 or 503 error with body messages similar to what's mentioned below. A restart/redeploy of the pods resolves the issue for a period of time.

```curl
< HTTP/1.1 503 Service Unavailable
< l5d-err: exceeded+10.seconds+to+unspecified+while+dyn+binding+%2Fsvc%redactedip%3A9990.+Remote+Info%3A+Not+Available
```
```curl
< HTTP/1.1 502 Bad Gateway
< l5d-err: connection+timed+out%3A+06-mTLS.redact%2Fredactedip%3A443+at+remote+address%3A+06-mTLS.redact%2Fredactedip%3A443.+Remote+Info%3A+Not+Available
```

l5d container logs show a number of entries that include the following types of messages. In the following example, 30-disableTLS.redact represents a service external to the k8s cluster which has been independently tested for availability:

```
I 0406 15:09:51.270 UTC THREAD1: linkerd 1.3.6 (rev=48a2a63d47fd0f6713c74ec03b8588bbc067e1de) built at 20180302-132344
I 0406 15:09:51.931 UTC THREAD1: Finagle version 7.1.0 (rev=37212517b530319f4ba08cc7473c8cd8c4b83479) built at 20170906-132024
...
I 0408 01:40:19.690 UTC THREAD4040 TraceId:c72cef050406abeb: $/io.buoyant.rinet/11102/30-disableTLS.redact: name resolution is negative (local dtab: Dtab())
E 0408 01:40:19.693 UTC THREAD4040 TraceId:c72cef050406abeb: service failure: com.twitter.finagle.NoBrokersAvailableException: No hosts are available for /svc/30-disableTLS.redact:11102, Dtab.base=[], Dtab.local=[]. Remote Info: Not Available
I 0408 01:40:24.670 UTC THREAD4040 TraceId:c72cef050406abeb: $/io.buoyant.rinet/11102/30-disableTLS.redact: name resolution is negative (local dtab: Dtab())
I 0408 01:40:29.680 UTC THREAD4040 TraceId:c72cef050406abeb: $/io.buoyant.rinet/11102/30-disableTLS.redact: name resolution is negative (local dtab: Dtab())
```
There are also a large number of errors logged of the following form:

```
I 0516 17:09:01.872 UTC THREAD1: linkerd 1.3.7 (rev=7cc7b8dc69287f442c8f22fed04fb1910246b896) built at 20180405-145503
I 0516 17:09:02.415 UTC THREAD1: Finagle version 7.1.0 (rev=37212517b530319f4ba08cc7473c8cd8c4b83479) built at 20170906-132024
...
W 0516 21:22:11.238 UTC THREAD14: retrying k8s request to /api/v1/namespaces/com:7443/endpoints/redactname3 on error com.twitter.io.Reader$ReaderDiscarded: This writer's reader has been discarded
W 0516 21:22:11.243 UTC THREAD14 TraceId:d4eb4997f5f72ec4: Exception propagated to the default monitor (upstream address: /x.x.x.x:34186, downstream address: localhost/x.x.x.x:8001, label: client).
com.twitter.io.Reader$ReaderDiscarded: This writer's reader has been discarded
```

**What you expected to happen**: 
All l5d pods consistently route without degradation

**How to reproduce it (as minimally and precisely as possible)**: 
Unclear

**Anything else we need to know?**: 
Heapdumps sent privately

**Environment**:
- linkerd/namerd version, config files: 
l5d 1.3.6, 1.3.7 daemonset install with configmap
[configmap.yml.txt](https://github.com/linkerd/linkerd/files/2070136/configmap.yml.txt)
[linkerd.yml.txt](https://github.com/linkerd/linkerd/files/2070137/linkerd.yml.txt)

- Platform, version, and config files (Kubernetes, DC/OS, etc): 
kubernetes 1.7, 1.8

- Cloud provider or hardware configuration: 
AWS

**Comment by adleong** [comment] 2018-06-04 22:41
This error message `$/io.buoyant.rinet/11102/30-disableTLS.redact: name resolution is negative` indicates that Linkerd could not resolve the DNS name `30-disableTLS.redact`.  How did you independently test this for availability?  Are you able to resolve this DNS name from within the Linkerd pod?

**Comment by betson-nuovo** [comment] 2018-06-04 22:54
Yes, that's correct. An independent curl from within the l5d pod, direct to the target endpoint without proxying through l5d.

**Comment by adleong** [comment] 2018-06-04 22:58
Well now that _is_ strange.  As far as I know, Linkerd uses the JVM's built-in DNS resolver.  I wonder if this is some kind of DNS caching issue in the JVM.  Do you know if these failures are corellated with changes to the DNS record?

**Comment by betson-nuovo** [comment] 2018-06-04 23:04
Not that I'm aware of after initial configuration. It is possible when we are first configuring a new endpoint that DNS record changes are in-flight, but I believe those remain mostly static for a particular endpoint after initial configuration. These particular endpoints are owned by a different group, so I can't say for certain. I can try to do a bit of digging there

**Comment by adleong** [comment] 2018-06-04 23:18
Using some of the search options with the command line utility `dig` might help uncover if anything funny is going on with DNS resolution that the JVM is missing.

**Comment by adleong** [comment] 2018-06-12 20:41
Any luck tracking this down?  Any signs pointing to whether this is a Linkerd issue or a DNS issue?

**Comment by adleong** [comment] 2018-06-14 20:02
I'm not sure the heapdumps will be of much use since this appears to be an issue with DNS resolution in the JVM.

**Comment by adleong** [comment] 2018-06-26 20:45
@betson-nuovo any update from your colleague who has been investigating the DNS issue?  On our side there's not much we can do to investigate further.

**Comment by zillani-nuovo** [comment] 2018-06-28 13:05
@adleong I am working on reproducing the issue under same conditions where this was reported, I want to load test the setup up for few days. I will update you soon, thanks for the support!

**Comment by adleong** [comment] 2018-07-10 20:46
@zillani-nuovo are you still seeing this?  Should we close this issue?

**Comment by zillani-nuovo** [comment] 2018-07-12 14:54
Hey, @adleong thanks for checking, we noticed the issue again today, and I have sent you the dig logs.
currently, we are restarting the pods for fixing the issue & the dnspolicy is ClusterFirstWithHostNet

**Comment by adleong** [comment] 2018-07-23 15:03
@zillani-nuovo I believe that investigation of this issue has moved to email.  Do you mind if we close this issue on Github?

**Comment by zillani** [comment] 2018-07-23 15:08
@adleong Sure, thanks for the follow-up.

**Closed** 2018-07-23 15:17 UTC
